// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/embedpdf/cloudpdf-sdk-go/v3/core"
	deployment "github.com/embedpdf/cloudpdf-sdk-go/v3/deployment"
	client "github.com/embedpdf/cloudpdf-sdk-go/v3/doc/client"
	documents "github.com/embedpdf/cloudpdf-sdk-go/v3/documents"
	internal "github.com/embedpdf/cloudpdf-sdk-go/v3/internal"
	option "github.com/embedpdf/cloudpdf-sdk-go/v3/option"
	tenants "github.com/embedpdf/cloudpdf-sdk-go/v3/tenants"
	tokens "github.com/embedpdf/cloudpdf-sdk-go/v3/tokens"
)

type Client struct {
	Deployment *deployment.Client
	Doc        *client.Client
	Tenants    *tenants.Client
	Documents  *documents.Client
	Tokens     *tokens.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Deployment: deployment.NewClient(options),
		Doc:        client.NewClient(options),
		Tenants:    tenants.NewClient(options),
		Documents:  documents.NewClient(options),
		Tokens:     tokens.NewClient(options),
		options:    options,
		baseURL:    options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
