// Code generated by Fern. DO NOT EDIT.

package shares

import (
	context "context"

	cloudpdf "github.com/embedpdf/cloudpdf-sdk-go/v3"
	core "github.com/embedpdf/cloudpdf-sdk-go/v3/core"
	internal "github.com/embedpdf/cloudpdf-sdk-go/v3/internal"
	option "github.com/embedpdf/cloudpdf-sdk-go/v3/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Unauthenticated, but requires a browser Origin header, checked against the grant allowlist. Unknown, revoked, and disabled tokens are indistinguishable (404). Passphrase-protected grants return 422 SharePasswordRequired until `password` is supplied. Mounted only when the deployment can sign (HS256 mode).
//
// Example:
//
//	request := &cloudpdf.SharesExchangeRequest{
//	    ShareToken: "shareToken",
//	}
//	client.Shares.Exchange(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Exchange(
	ctx context.Context,
	request *cloudpdf.SharesExchangeRequest,
	opts ...option.RequestOption,
) (*cloudpdf.SharesExchange200Response, error) {
	response, err := c.WithRawResponse.Exchange(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &cloudpdf.ListSharesRequest{
//	    TenantID: "tenantId",
//	}
//	client.Shares.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *cloudpdf.ListSharesRequest,
	opts ...option.RequestOption,
) (*cloudpdf.SharesList200Response, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The returned share id IS the public share token. Mounted only when the deployment can sign (HS256 mode) — exchange mints session JWTs, so grants exist only where minting does.
//
// Example:
//
//	request := &cloudpdf.SharesCreateRequest{
//	    TenantID: "tenantId",
//	    DocID: "docId",
//	    Scope: []string{
//	        "scope",
//	    },
//	}
//	client.Shares.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *cloudpdf.SharesCreateRequest,
	opts ...option.RequestOption,
) (*cloudpdf.SharesCreate200Response, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &cloudpdf.GetSharesRequest{
//	    TenantID: "tenantId",
//	    ShareID: "shareId",
//	}
//	client.Shares.Get(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Get(
	ctx context.Context,
	request *cloudpdf.GetSharesRequest,
	opts ...option.RequestOption,
) (*cloudpdf.SharesGet200Response, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &cloudpdf.DeleteSharesRequest{
//	    TenantID: "tenantId",
//	    ShareID: "shareId",
//	}
//	client.Shares.Delete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Delete(
	ctx context.Context,
	request *cloudpdf.DeleteSharesRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Example:
//
//	request := &cloudpdf.SharesUpdateRequest{
//	    TenantID: "tenantId",
//	    ShareID: "shareId",
//	}
//	client.Shares.Update(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Update(
	ctx context.Context,
	request *cloudpdf.SharesUpdateRequest,
	opts ...option.RequestOption,
) (*cloudpdf.SharesUpdate200Response, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
