// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"
	io "io"

	cloudpdf "github.com/embedpdf/cloudpdf-sdk-go/v3"
	core "github.com/embedpdf/cloudpdf-sdk-go/v3/core"
	annotations "github.com/embedpdf/cloudpdf-sdk-go/v3/doc/annotations"
	forms "github.com/embedpdf/cloudpdf-sdk-go/v3/doc/forms"
	metadata "github.com/embedpdf/cloudpdf-sdk-go/v3/doc/metadata"
	pages "github.com/embedpdf/cloudpdf-sdk-go/v3/doc/pages"
	redactions "github.com/embedpdf/cloudpdf-sdk-go/v3/doc/redactions"
	internal "github.com/embedpdf/cloudpdf-sdk-go/v3/internal"
	option "github.com/embedpdf/cloudpdf-sdk-go/v3/option"
)

type Client struct {
	WithRawResponse *RawClient
	Annotations     *annotations.Client
	Forms           *forms.Client
	Metadata        *metadata.Client
	Pages           *pages.Client
	Redactions      *redactions.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Annotations:     annotations.NewClient(options),
		Forms:           forms.NewClient(options),
		Metadata:        metadata.NewClient(options),
		Pages:           pages.NewClient(options),
		Redactions:      redactions.NewClient(options),
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	request := &cloudpdf.HeadDocRequest{
//	    DocID: "docId",
//	}
//	client.Doc.Head(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Head(
	ctx context.Context,
	request *cloudpdf.HeadDocRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocHead200Response, error) {
	response, err := c.WithRawResponse.Head(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &cloudpdf.DownloadDocRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	}
//	client.Doc.Download(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Download(
	ctx context.Context,
	request *cloudpdf.DownloadDocRequest,
	opts ...option.RequestOption,
) (io.Reader, error) {
	response, err := c.WithRawResponse.Download(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &cloudpdf.ManifestDocRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	}
//	client.Doc.Manifest(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Manifest(
	ctx context.Context,
	request *cloudpdf.ManifestDocRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocManifest200Response, error) {
	response, err := c.WithRawResponse.Manifest(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Render parameters (viewport, format) pass as flat dotted query keys, e.g. `?viewport.kind=width&viewport.width=800`; the full grammar is documented with the viewer.
//
// Example:
//
//	request := &cloudpdf.RenderDocRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Pon: 1,
//	}
//	client.Doc.Render(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Render(
	ctx context.Context,
	request *cloudpdf.RenderDocRequest,
	opts ...option.RequestOption,
) (io.Reader, error) {
	response, err := c.WithRawResponse.Render(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &cloudpdf.TextDocRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Pon: 1,
//	}
//	client.Doc.Text(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Text(
	ctx context.Context,
	request *cloudpdf.TextDocRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocText200Response, error) {
	response, err := c.WithRawResponse.Text(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
