// Code generated by Fern. DO NOT EDIT.

package documents

import (
	context "context"
	io "io"

	cloudpdf "github.com/embedpdf/cloudpdf-sdk-go/v3"
	core "github.com/embedpdf/cloudpdf-sdk-go/v3/core"
	internal "github.com/embedpdf/cloudpdf-sdk-go/v3/internal"
	option "github.com/embedpdf/cloudpdf-sdk-go/v3/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	request := &cloudpdf.ListDocumentsRequest{
//	    TenantID: "tenantId",
//	}
//	client.Documents.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *cloudpdf.ListDocumentsRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocumentsList200Response, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &cloudpdf.GetDocumentsRequest{
//	    TenantID: "tenantId",
//	    ID: "id",
//	}
//	client.Documents.Get(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Get(
	ctx context.Context,
	request *cloudpdf.GetDocumentsRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocumentsGet200Response, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &cloudpdf.DeleteDocumentsRequest{
//	    TenantID: "tenantId",
//	    ID: "id",
//	}
//	client.Documents.Delete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Delete(
	ctx context.Context,
	request *cloudpdf.DeleteDocumentsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Example:
//
//	request := &cloudpdf.DocumentsCommitRequest{
//	    TenantID: "tenantId",
//	    ID: "id",
//	    Sha256: "sha256",
//	}
//	client.Documents.Commit(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Commit(
	ctx context.Context,
	request *cloudpdf.DocumentsCommitRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocumentsCommit200Response, error) {
	response, err := c.WithRawResponse.Commit(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &cloudpdf.DownloadDocumentsRequest{
//	    TenantID: "tenantId",
//	    ID: "id",
//	}
//	client.Documents.Download(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Download(
	ctx context.Context,
	request *cloudpdf.DownloadDocumentsRequest,
	opts ...option.RequestOption,
) (io.Reader, error) {
	response, err := c.WithRawResponse.Download(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &cloudpdf.ThumbnailDocumentsRequest{
//	    TenantID: "tenantId",
//	    ID: "id",
//	}
//	client.Documents.Thumbnail(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Thumbnail(
	ctx context.Context,
	request *cloudpdf.ThumbnailDocumentsRequest,
	opts ...option.RequestOption,
) (io.Reader, error) {
	response, err := c.WithRawResponse.Thumbnail(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) UploadDirect(
	ctx context.Context,
	tenantID string,
	id string,
	request io.Reader,
	opts ...option.RequestOption,
) (*cloudpdf.DocumentsUploadDirect200Response, error) {
	response, err := c.WithRawResponse.UploadDirect(
		ctx,
		tenantID,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &cloudpdf.DocumentsInitRequest{
//	    TenantID: "tenantId",
//	    ContentLength: 1.1,
//	    ContentSha256: "contentSha256",
//	}
//	client.Documents.Init(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Init(
	ctx context.Context,
	request *cloudpdf.DocumentsInitRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocumentsInit200Response, error) {
	response, err := c.WithRawResponse.Init(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
