// Code generated by Fern. DO NOT EDIT.

package cloudpdf

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/embedpdf/cloudpdf-sdk-go/v3/internal"
	big "math/big"
)

var (
	deploymentLicenseStatusResponseFieldLicense   = big.NewInt(1 << 0)
	deploymentLicenseStatusResponseFieldReporting = big.NewInt(1 << 1)
	deploymentLicenseStatusResponseFieldUsage     = big.NewInt(1 << 2)
)

type DeploymentLicenseStatusResponse struct {
	License   any `json:"license,omitempty" url:"license,omitempty"`
	Reporting any `json:"reporting,omitempty" url:"reporting,omitempty"`
	Usage     any `json:"usage,omitempty" url:"usage,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeploymentLicenseStatusResponse) GetLicense() any {
	if d == nil {
		return nil
	}
	return d.License
}

func (d *DeploymentLicenseStatusResponse) GetReporting() any {
	if d == nil {
		return nil
	}
	return d.Reporting
}

func (d *DeploymentLicenseStatusResponse) GetUsage() any {
	if d == nil {
		return nil
	}
	return d.Usage
}

func (d *DeploymentLicenseStatusResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeploymentLicenseStatusResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetLicense sets the License field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeploymentLicenseStatusResponse) SetLicense(license any) {
	d.License = license
	d.require(deploymentLicenseStatusResponseFieldLicense)
}

// SetReporting sets the Reporting field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeploymentLicenseStatusResponse) SetReporting(reporting any) {
	d.Reporting = reporting
	d.require(deploymentLicenseStatusResponseFieldReporting)
}

// SetUsage sets the Usage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeploymentLicenseStatusResponse) SetUsage(usage any) {
	d.Usage = usage
	d.require(deploymentLicenseStatusResponseFieldUsage)
}

func (d *DeploymentLicenseStatusResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeploymentLicenseStatusResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeploymentLicenseStatusResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeploymentLicenseStatusResponse) MarshalJSON() ([]byte, error) {
	type embed DeploymentLicenseStatusResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeploymentLicenseStatusResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}
