// Code generated by Fern. DO NOT EDIT.

package cloudpdf

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/embedpdf/cloudpdf-sdk-go/v3/internal"
	big "math/big"
)

var (
	downloadDocRequestFieldDocumentPassword = big.NewInt(1 << 0)
	downloadDocRequestFieldDocID            = big.NewInt(1 << 1)
	downloadDocRequestFieldLayerName        = big.NewInt(1 << 2)
)

type DownloadDocRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string `json:"-" url:"-"`
	DocID            string  `json:"-" url:"-"`
	LayerName        string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DownloadDocRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadDocRequest) SetDocumentPassword(documentPassword *string) {
	d.DocumentPassword = documentPassword
	d.require(downloadDocRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadDocRequest) SetDocID(docID string) {
	d.DocID = docID
	d.require(downloadDocRequestFieldDocID)
}

// SetLayerName sets the LayerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadDocRequest) SetLayerName(layerName string) {
	d.LayerName = layerName
	d.require(downloadDocRequestFieldLayerName)
}

var (
	headDocRequestFieldDocumentPassword = big.NewInt(1 << 0)
	headDocRequestFieldDocID            = big.NewInt(1 << 1)
)

type HeadDocRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string `json:"-" url:"-"`
	DocID            string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (h *HeadDocRequest) require(field *big.Int) {
	if h.explicitFields == nil {
		h.explicitFields = big.NewInt(0)
	}
	h.explicitFields.Or(h.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HeadDocRequest) SetDocumentPassword(documentPassword *string) {
	h.DocumentPassword = documentPassword
	h.require(headDocRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HeadDocRequest) SetDocID(docID string) {
	h.DocID = docID
	h.require(headDocRequestFieldDocID)
}

var (
	manifestDocRequestFieldDocumentPassword = big.NewInt(1 << 0)
	manifestDocRequestFieldDocID            = big.NewInt(1 << 1)
	manifestDocRequestFieldLayerName        = big.NewInt(1 << 2)
)

type ManifestDocRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string `json:"-" url:"-"`
	DocID            string  `json:"-" url:"-"`
	LayerName        string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *ManifestDocRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ManifestDocRequest) SetDocumentPassword(documentPassword *string) {
	m.DocumentPassword = documentPassword
	m.require(manifestDocRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ManifestDocRequest) SetDocID(docID string) {
	m.DocID = docID
	m.require(manifestDocRequestFieldDocID)
}

// SetLayerName sets the LayerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ManifestDocRequest) SetLayerName(layerName string) {
	m.LayerName = layerName
	m.require(manifestDocRequestFieldLayerName)
}

var (
	renderDocRequestFieldDocumentPassword = big.NewInt(1 << 0)
	renderDocRequestFieldDocID            = big.NewInt(1 << 1)
	renderDocRequestFieldLayerName        = big.NewInt(1 << 2)
	renderDocRequestFieldPon              = big.NewInt(1 << 3)
)

type RenderDocRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string `json:"-" url:"-"`
	DocID            string  `json:"-" url:"-"`
	LayerName        string  `json:"-" url:"-"`
	Pon              int     `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RenderDocRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RenderDocRequest) SetDocumentPassword(documentPassword *string) {
	r.DocumentPassword = documentPassword
	r.require(renderDocRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RenderDocRequest) SetDocID(docID string) {
	r.DocID = docID
	r.require(renderDocRequestFieldDocID)
}

// SetLayerName sets the LayerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RenderDocRequest) SetLayerName(layerName string) {
	r.LayerName = layerName
	r.require(renderDocRequestFieldLayerName)
}

// SetPon sets the Pon field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RenderDocRequest) SetPon(pon int) {
	r.Pon = pon
	r.require(renderDocRequestFieldPon)
}

var (
	textDocRequestFieldDocumentPassword = big.NewInt(1 << 0)
	textDocRequestFieldDocID            = big.NewInt(1 << 1)
	textDocRequestFieldLayerName        = big.NewInt(1 << 2)
	textDocRequestFieldPon              = big.NewInt(1 << 3)
)

type TextDocRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string `json:"-" url:"-"`
	DocID            string  `json:"-" url:"-"`
	LayerName        string  `json:"-" url:"-"`
	Pon              int     `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TextDocRequest) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TextDocRequest) SetDocumentPassword(documentPassword *string) {
	t.DocumentPassword = documentPassword
	t.require(textDocRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TextDocRequest) SetDocID(docID string) {
	t.DocID = docID
	t.require(textDocRequestFieldDocID)
}

// SetLayerName sets the LayerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TextDocRequest) SetLayerName(layerName string) {
	t.LayerName = layerName
	t.require(textDocRequestFieldLayerName)
}

// SetPon sets the Pon field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TextDocRequest) SetPon(pon int) {
	t.Pon = pon
	t.require(textDocRequestFieldPon)
}

var (
	docHead200ResponseFieldID               = big.NewInt(1 << 0)
	docHead200ResponseFieldBaseSha          = big.NewInt(1 << 1)
	docHead200ResponseFieldStorageSizeBytes = big.NewInt(1 << 2)
	docHead200ResponseFieldDocVersion       = big.NewInt(1 << 3)
	docHead200ResponseFieldState            = big.NewInt(1 << 4)
	docHead200ResponseFieldEncryption       = big.NewInt(1 << 5)
	docHead200ResponseFieldPermissions      = big.NewInt(1 << 6)
	docHead200ResponseFieldAccess           = big.NewInt(1 << 7)
)

type DocHead200Response struct {
	ID               string                         `json:"id" url:"id"`
	BaseSha          string                         `json:"baseSha" url:"baseSha"`
	StorageSizeBytes int                            `json:"storageSizeBytes" url:"storageSizeBytes"`
	DocVersion       int                            `json:"docVersion" url:"docVersion"`
	State            DocHead200ResponseState        `json:"state" url:"state"`
	Encryption       *DocHead200ResponseEncryption  `json:"encryption" url:"encryption"`
	Permissions      *DocHead200ResponsePermissions `json:"permissions" url:"permissions"`
	Access           *DocHead200ResponseAccess      `json:"access" url:"access"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DocHead200Response) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DocHead200Response) GetBaseSha() string {
	if d == nil {
		return ""
	}
	return d.BaseSha
}

func (d *DocHead200Response) GetStorageSizeBytes() int {
	if d == nil {
		return 0
	}
	return d.StorageSizeBytes
}

func (d *DocHead200Response) GetDocVersion() int {
	if d == nil {
		return 0
	}
	return d.DocVersion
}

func (d *DocHead200Response) GetState() DocHead200ResponseState {
	if d == nil {
		return ""
	}
	return d.State
}

func (d *DocHead200Response) GetEncryption() *DocHead200ResponseEncryption {
	if d == nil {
		return nil
	}
	return d.Encryption
}

func (d *DocHead200Response) GetPermissions() *DocHead200ResponsePermissions {
	if d == nil {
		return nil
	}
	return d.Permissions
}

func (d *DocHead200Response) GetAccess() *DocHead200ResponseAccess {
	if d == nil {
		return nil
	}
	return d.Access
}

func (d *DocHead200Response) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DocHead200Response) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200Response) SetID(id string) {
	d.ID = id
	d.require(docHead200ResponseFieldID)
}

// SetBaseSha sets the BaseSha field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200Response) SetBaseSha(baseSha string) {
	d.BaseSha = baseSha
	d.require(docHead200ResponseFieldBaseSha)
}

// SetStorageSizeBytes sets the StorageSizeBytes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200Response) SetStorageSizeBytes(storageSizeBytes int) {
	d.StorageSizeBytes = storageSizeBytes
	d.require(docHead200ResponseFieldStorageSizeBytes)
}

// SetDocVersion sets the DocVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200Response) SetDocVersion(docVersion int) {
	d.DocVersion = docVersion
	d.require(docHead200ResponseFieldDocVersion)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200Response) SetState(state DocHead200ResponseState) {
	d.State = state
	d.require(docHead200ResponseFieldState)
}

// SetEncryption sets the Encryption field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200Response) SetEncryption(encryption *DocHead200ResponseEncryption) {
	d.Encryption = encryption
	d.require(docHead200ResponseFieldEncryption)
}

// SetPermissions sets the Permissions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200Response) SetPermissions(permissions *DocHead200ResponsePermissions) {
	d.Permissions = permissions
	d.require(docHead200ResponseFieldPermissions)
}

// SetAccess sets the Access field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200Response) SetAccess(access *DocHead200ResponseAccess) {
	d.Access = access
	d.require(docHead200ResponseFieldAccess)
}

func (d *DocHead200Response) UnmarshalJSON(data []byte) error {
	type unmarshaler DocHead200Response
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DocHead200Response(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DocHead200Response) MarshalJSON() ([]byte, error) {
	type embed DocHead200Response
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DocHead200Response) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	docHead200ResponseAccessFieldRequired = big.NewInt(1 << 0)
	docHead200ResponseAccessFieldReasons  = big.NewInt(1 << 1)
	docHead200ResponseAccessFieldEndpoint = big.NewInt(1 << 2)
)

type DocHead200ResponseAccess struct {
	Required bool                                  `json:"required" url:"required"`
	Reasons  []DocHead200ResponseAccessReasonsItem `json:"reasons" url:"reasons"`
	Endpoint *string                               `json:"endpoint,omitempty" url:"endpoint,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DocHead200ResponseAccess) GetRequired() bool {
	if d == nil {
		return false
	}
	return d.Required
}

func (d *DocHead200ResponseAccess) GetReasons() []DocHead200ResponseAccessReasonsItem {
	if d == nil {
		return nil
	}
	return d.Reasons
}

func (d *DocHead200ResponseAccess) GetEndpoint() *string {
	if d == nil {
		return nil
	}
	return d.Endpoint
}

func (d *DocHead200ResponseAccess) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DocHead200ResponseAccess) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetRequired sets the Required field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200ResponseAccess) SetRequired(required bool) {
	d.Required = required
	d.require(docHead200ResponseAccessFieldRequired)
}

// SetReasons sets the Reasons field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200ResponseAccess) SetReasons(reasons []DocHead200ResponseAccessReasonsItem) {
	d.Reasons = reasons
	d.require(docHead200ResponseAccessFieldReasons)
}

// SetEndpoint sets the Endpoint field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200ResponseAccess) SetEndpoint(endpoint *string) {
	d.Endpoint = endpoint
	d.require(docHead200ResponseAccessFieldEndpoint)
}

func (d *DocHead200ResponseAccess) UnmarshalJSON(data []byte) error {
	type unmarshaler DocHead200ResponseAccess
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DocHead200ResponseAccess(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DocHead200ResponseAccess) MarshalJSON() ([]byte, error) {
	type embed DocHead200ResponseAccess
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DocHead200ResponseAccess) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DocHead200ResponseAccessReasonsItem string

const (
	DocHead200ResponseAccessReasonsItemPassword           DocHead200ResponseAccessReasonsItem = "password"
	DocHead200ResponseAccessReasonsItemCdn                DocHead200ResponseAccessReasonsItem = "cdn"
	DocHead200ResponseAccessReasonsItemPermissionsUnknown DocHead200ResponseAccessReasonsItem = "permissions-unknown"
)

func NewDocHead200ResponseAccessReasonsItemFromString(s string) (DocHead200ResponseAccessReasonsItem, error) {
	switch s {
	case "password":
		return DocHead200ResponseAccessReasonsItemPassword, nil
	case "cdn":
		return DocHead200ResponseAccessReasonsItemCdn, nil
	case "permissions-unknown":
		return DocHead200ResponseAccessReasonsItemPermissionsUnknown, nil
	}
	var t DocHead200ResponseAccessReasonsItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DocHead200ResponseAccessReasonsItem) Ptr() *DocHead200ResponseAccessReasonsItem {
	return &d
}

var (
	docHead200ResponseEncryptionFieldState            = big.NewInt(1 << 0)
	docHead200ResponseEncryptionFieldRequiresPassword = big.NewInt(1 << 1)
)

type DocHead200ResponseEncryption struct {
	State            DocHead200ResponseEncryptionState `json:"state" url:"state"`
	RequiresPassword *bool                             `json:"requiresPassword,omitempty" url:"requiresPassword,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DocHead200ResponseEncryption) GetState() DocHead200ResponseEncryptionState {
	if d == nil {
		return ""
	}
	return d.State
}

func (d *DocHead200ResponseEncryption) GetRequiresPassword() *bool {
	if d == nil {
		return nil
	}
	return d.RequiresPassword
}

func (d *DocHead200ResponseEncryption) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DocHead200ResponseEncryption) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200ResponseEncryption) SetState(state DocHead200ResponseEncryptionState) {
	d.State = state
	d.require(docHead200ResponseEncryptionFieldState)
}

// SetRequiresPassword sets the RequiresPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200ResponseEncryption) SetRequiresPassword(requiresPassword *bool) {
	d.RequiresPassword = requiresPassword
	d.require(docHead200ResponseEncryptionFieldRequiresPassword)
}

func (d *DocHead200ResponseEncryption) UnmarshalJSON(data []byte) error {
	type unmarshaler DocHead200ResponseEncryption
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DocHead200ResponseEncryption(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DocHead200ResponseEncryption) MarshalJSON() ([]byte, error) {
	type embed DocHead200ResponseEncryption
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DocHead200ResponseEncryption) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DocHead200ResponseEncryptionState string

const (
	DocHead200ResponseEncryptionStateUnknown     DocHead200ResponseEncryptionState = "unknown"
	DocHead200ResponseEncryptionStateNone        DocHead200ResponseEncryptionState = "none"
	DocHead200ResponseEncryptionStateEncrypted   DocHead200ResponseEncryptionState = "encrypted"
	DocHead200ResponseEncryptionStateUnsupported DocHead200ResponseEncryptionState = "unsupported"
)

func NewDocHead200ResponseEncryptionStateFromString(s string) (DocHead200ResponseEncryptionState, error) {
	switch s {
	case "unknown":
		return DocHead200ResponseEncryptionStateUnknown, nil
	case "none":
		return DocHead200ResponseEncryptionStateNone, nil
	case "encrypted":
		return DocHead200ResponseEncryptionStateEncrypted, nil
	case "unsupported":
		return DocHead200ResponseEncryptionStateUnsupported, nil
	}
	var t DocHead200ResponseEncryptionState
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DocHead200ResponseEncryptionState) Ptr() *DocHead200ResponseEncryptionState {
	return &d
}

var (
	docHead200ResponsePermissionsFieldKnown                   = big.NewInt(1 << 0)
	docHead200ResponsePermissionsFieldBits                    = big.NewInt(1 << 1)
	docHead200ResponsePermissionsFieldAllAllowed              = big.NewInt(1 << 2)
	docHead200ResponsePermissionsFieldOpenedAs                = big.NewInt(1 << 3)
	docHead200ResponsePermissionsFieldSecurityHandlerRevision = big.NewInt(1 << 4)
	docHead200ResponsePermissionsFieldCanUpgradeToOwner       = big.NewInt(1 << 5)
)

type DocHead200ResponsePermissions struct {
	Known                   bool                                   `json:"known" url:"known"`
	Bits                    *int                                   `json:"bits,omitempty" url:"bits,omitempty"`
	AllAllowed              *bool                                  `json:"allAllowed,omitempty" url:"allAllowed,omitempty"`
	OpenedAs                *DocHead200ResponsePermissionsOpenedAs `json:"openedAs,omitempty" url:"openedAs,omitempty"`
	SecurityHandlerRevision *int                                   `json:"securityHandlerRevision,omitempty" url:"securityHandlerRevision,omitempty"`
	CanUpgradeToOwner       bool                                   `json:"canUpgradeToOwner" url:"canUpgradeToOwner"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DocHead200ResponsePermissions) GetKnown() bool {
	if d == nil {
		return false
	}
	return d.Known
}

func (d *DocHead200ResponsePermissions) GetBits() *int {
	if d == nil {
		return nil
	}
	return d.Bits
}

func (d *DocHead200ResponsePermissions) GetAllAllowed() *bool {
	if d == nil {
		return nil
	}
	return d.AllAllowed
}

func (d *DocHead200ResponsePermissions) GetOpenedAs() *DocHead200ResponsePermissionsOpenedAs {
	if d == nil {
		return nil
	}
	return d.OpenedAs
}

func (d *DocHead200ResponsePermissions) GetSecurityHandlerRevision() *int {
	if d == nil {
		return nil
	}
	return d.SecurityHandlerRevision
}

func (d *DocHead200ResponsePermissions) GetCanUpgradeToOwner() bool {
	if d == nil {
		return false
	}
	return d.CanUpgradeToOwner
}

func (d *DocHead200ResponsePermissions) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DocHead200ResponsePermissions) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetKnown sets the Known field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200ResponsePermissions) SetKnown(known bool) {
	d.Known = known
	d.require(docHead200ResponsePermissionsFieldKnown)
}

// SetBits sets the Bits field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200ResponsePermissions) SetBits(bits *int) {
	d.Bits = bits
	d.require(docHead200ResponsePermissionsFieldBits)
}

// SetAllAllowed sets the AllAllowed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200ResponsePermissions) SetAllAllowed(allAllowed *bool) {
	d.AllAllowed = allAllowed
	d.require(docHead200ResponsePermissionsFieldAllAllowed)
}

// SetOpenedAs sets the OpenedAs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200ResponsePermissions) SetOpenedAs(openedAs *DocHead200ResponsePermissionsOpenedAs) {
	d.OpenedAs = openedAs
	d.require(docHead200ResponsePermissionsFieldOpenedAs)
}

// SetSecurityHandlerRevision sets the SecurityHandlerRevision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200ResponsePermissions) SetSecurityHandlerRevision(securityHandlerRevision *int) {
	d.SecurityHandlerRevision = securityHandlerRevision
	d.require(docHead200ResponsePermissionsFieldSecurityHandlerRevision)
}

// SetCanUpgradeToOwner sets the CanUpgradeToOwner field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocHead200ResponsePermissions) SetCanUpgradeToOwner(canUpgradeToOwner bool) {
	d.CanUpgradeToOwner = canUpgradeToOwner
	d.require(docHead200ResponsePermissionsFieldCanUpgradeToOwner)
}

func (d *DocHead200ResponsePermissions) UnmarshalJSON(data []byte) error {
	type unmarshaler DocHead200ResponsePermissions
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DocHead200ResponsePermissions(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DocHead200ResponsePermissions) MarshalJSON() ([]byte, error) {
	type embed DocHead200ResponsePermissions
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DocHead200ResponsePermissions) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DocHead200ResponsePermissionsOpenedAs string

const (
	DocHead200ResponsePermissionsOpenedAsNone  DocHead200ResponsePermissionsOpenedAs = "none"
	DocHead200ResponsePermissionsOpenedAsUser  DocHead200ResponsePermissionsOpenedAs = "user"
	DocHead200ResponsePermissionsOpenedAsOwner DocHead200ResponsePermissionsOpenedAs = "owner"
)

func NewDocHead200ResponsePermissionsOpenedAsFromString(s string) (DocHead200ResponsePermissionsOpenedAs, error) {
	switch s {
	case "none":
		return DocHead200ResponsePermissionsOpenedAsNone, nil
	case "user":
		return DocHead200ResponsePermissionsOpenedAsUser, nil
	case "owner":
		return DocHead200ResponsePermissionsOpenedAsOwner, nil
	}
	var t DocHead200ResponsePermissionsOpenedAs
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DocHead200ResponsePermissionsOpenedAs) Ptr() *DocHead200ResponsePermissionsOpenedAs {
	return &d
}

type DocHead200ResponseState string

const (
	DocHead200ResponseStatePending  DocHead200ResponseState = "pending"
	DocHead200ResponseStateReady    DocHead200ResponseState = "ready"
	DocHead200ResponseStateFailed   DocHead200ResponseState = "failed"
	DocHead200ResponseStateDeleting DocHead200ResponseState = "deleting"
)

func NewDocHead200ResponseStateFromString(s string) (DocHead200ResponseState, error) {
	switch s {
	case "pending":
		return DocHead200ResponseStatePending, nil
	case "ready":
		return DocHead200ResponseStateReady, nil
	case "failed":
		return DocHead200ResponseStateFailed, nil
	case "deleting":
		return DocHead200ResponseStateDeleting, nil
	}
	var t DocHead200ResponseState
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DocHead200ResponseState) Ptr() *DocHead200ResponseState {
	return &d
}

var (
	docManifest200ResponseFieldDocVersion         = big.NewInt(1 << 0)
	docManifest200ResponseFieldLayoutVersion      = big.NewInt(1 << 1)
	docManifest200ResponseFieldMetadataVersion    = big.NewInt(1 << 2)
	docManifest200ResponseFieldActionsVersion     = big.NewInt(1 << 3)
	docManifest200ResponseFieldAttachmentsVersion = big.NewInt(1 << 4)
	docManifest200ResponseFieldAuditHead          = big.NewInt(1 << 5)
	docManifest200ResponseFieldBaseSha            = big.NewInt(1 << 6)
	docManifest200ResponseFieldScopes             = big.NewInt(1 << 7)
	docManifest200ResponseFieldPages              = big.NewInt(1 << 8)
)

type DocManifest200Response struct {
	DocVersion         int                                `json:"docVersion" url:"docVersion"`
	LayoutVersion      int                                `json:"layoutVersion" url:"layoutVersion"`
	MetadataVersion    int                                `json:"metadataVersion" url:"metadataVersion"`
	ActionsVersion     *int                               `json:"actionsVersion,omitempty" url:"actionsVersion,omitempty"`
	AttachmentsVersion *int                               `json:"attachmentsVersion,omitempty" url:"attachmentsVersion,omitempty"`
	AuditHead          int                                `json:"auditHead" url:"auditHead"`
	BaseSha            string                             `json:"baseSha" url:"baseSha"`
	Scopes             *DocManifest200ResponseScopes      `json:"scopes,omitempty" url:"scopes,omitempty"`
	Pages              []*DocManifest200ResponsePagesItem `json:"pages" url:"pages"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DocManifest200Response) GetDocVersion() int {
	if d == nil {
		return 0
	}
	return d.DocVersion
}

func (d *DocManifest200Response) GetLayoutVersion() int {
	if d == nil {
		return 0
	}
	return d.LayoutVersion
}

func (d *DocManifest200Response) GetMetadataVersion() int {
	if d == nil {
		return 0
	}
	return d.MetadataVersion
}

func (d *DocManifest200Response) GetActionsVersion() *int {
	if d == nil {
		return nil
	}
	return d.ActionsVersion
}

func (d *DocManifest200Response) GetAttachmentsVersion() *int {
	if d == nil {
		return nil
	}
	return d.AttachmentsVersion
}

func (d *DocManifest200Response) GetAuditHead() int {
	if d == nil {
		return 0
	}
	return d.AuditHead
}

func (d *DocManifest200Response) GetBaseSha() string {
	if d == nil {
		return ""
	}
	return d.BaseSha
}

func (d *DocManifest200Response) GetScopes() *DocManifest200ResponseScopes {
	if d == nil {
		return nil
	}
	return d.Scopes
}

func (d *DocManifest200Response) GetPages() []*DocManifest200ResponsePagesItem {
	if d == nil {
		return nil
	}
	return d.Pages
}

func (d *DocManifest200Response) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DocManifest200Response) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetDocVersion sets the DocVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200Response) SetDocVersion(docVersion int) {
	d.DocVersion = docVersion
	d.require(docManifest200ResponseFieldDocVersion)
}

// SetLayoutVersion sets the LayoutVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200Response) SetLayoutVersion(layoutVersion int) {
	d.LayoutVersion = layoutVersion
	d.require(docManifest200ResponseFieldLayoutVersion)
}

// SetMetadataVersion sets the MetadataVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200Response) SetMetadataVersion(metadataVersion int) {
	d.MetadataVersion = metadataVersion
	d.require(docManifest200ResponseFieldMetadataVersion)
}

// SetActionsVersion sets the ActionsVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200Response) SetActionsVersion(actionsVersion *int) {
	d.ActionsVersion = actionsVersion
	d.require(docManifest200ResponseFieldActionsVersion)
}

// SetAttachmentsVersion sets the AttachmentsVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200Response) SetAttachmentsVersion(attachmentsVersion *int) {
	d.AttachmentsVersion = attachmentsVersion
	d.require(docManifest200ResponseFieldAttachmentsVersion)
}

// SetAuditHead sets the AuditHead field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200Response) SetAuditHead(auditHead int) {
	d.AuditHead = auditHead
	d.require(docManifest200ResponseFieldAuditHead)
}

// SetBaseSha sets the BaseSha field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200Response) SetBaseSha(baseSha string) {
	d.BaseSha = baseSha
	d.require(docManifest200ResponseFieldBaseSha)
}

// SetScopes sets the Scopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200Response) SetScopes(scopes *DocManifest200ResponseScopes) {
	d.Scopes = scopes
	d.require(docManifest200ResponseFieldScopes)
}

// SetPages sets the Pages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200Response) SetPages(pages []*DocManifest200ResponsePagesItem) {
	d.Pages = pages
	d.require(docManifest200ResponseFieldPages)
}

func (d *DocManifest200Response) UnmarshalJSON(data []byte) error {
	type unmarshaler DocManifest200Response
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DocManifest200Response(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DocManifest200Response) MarshalJSON() ([]byte, error) {
	type embed DocManifest200Response
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DocManifest200Response) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	docManifest200ResponsePagesItemFieldState = big.NewInt(1 << 0)
	docManifest200ResponsePagesItemFieldCache = big.NewInt(1 << 1)
)

type DocManifest200ResponsePagesItem struct {
	State *DocManifest200ResponsePagesItemState `json:"state" url:"state"`
	Cache *DocManifest200ResponsePagesItemCache `json:"cache" url:"cache"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DocManifest200ResponsePagesItem) GetState() *DocManifest200ResponsePagesItemState {
	if d == nil {
		return nil
	}
	return d.State
}

func (d *DocManifest200ResponsePagesItem) GetCache() *DocManifest200ResponsePagesItemCache {
	if d == nil {
		return nil
	}
	return d.Cache
}

func (d *DocManifest200ResponsePagesItem) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DocManifest200ResponsePagesItem) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200ResponsePagesItem) SetState(state *DocManifest200ResponsePagesItemState) {
	d.State = state
	d.require(docManifest200ResponsePagesItemFieldState)
}

// SetCache sets the Cache field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200ResponsePagesItem) SetCache(cache *DocManifest200ResponsePagesItemCache) {
	d.Cache = cache
	d.require(docManifest200ResponsePagesItemFieldCache)
}

func (d *DocManifest200ResponsePagesItem) UnmarshalJSON(data []byte) error {
	type unmarshaler DocManifest200ResponsePagesItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DocManifest200ResponsePagesItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DocManifest200ResponsePagesItem) MarshalJSON() ([]byte, error) {
	type embed DocManifest200ResponsePagesItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DocManifest200ResponsePagesItem) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	docManifest200ResponsePagesItemCacheFieldContentVersion    = big.NewInt(1 << 0)
	docManifest200ResponsePagesItemCacheFieldAnnotationVersion = big.NewInt(1 << 1)
)

type DocManifest200ResponsePagesItemCache struct {
	ContentVersion    int `json:"contentVersion" url:"contentVersion"`
	AnnotationVersion int `json:"annotationVersion" url:"annotationVersion"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DocManifest200ResponsePagesItemCache) GetContentVersion() int {
	if d == nil {
		return 0
	}
	return d.ContentVersion
}

func (d *DocManifest200ResponsePagesItemCache) GetAnnotationVersion() int {
	if d == nil {
		return 0
	}
	return d.AnnotationVersion
}

func (d *DocManifest200ResponsePagesItemCache) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DocManifest200ResponsePagesItemCache) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetContentVersion sets the ContentVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200ResponsePagesItemCache) SetContentVersion(contentVersion int) {
	d.ContentVersion = contentVersion
	d.require(docManifest200ResponsePagesItemCacheFieldContentVersion)
}

// SetAnnotationVersion sets the AnnotationVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200ResponsePagesItemCache) SetAnnotationVersion(annotationVersion int) {
	d.AnnotationVersion = annotationVersion
	d.require(docManifest200ResponsePagesItemCacheFieldAnnotationVersion)
}

func (d *DocManifest200ResponsePagesItemCache) UnmarshalJSON(data []byte) error {
	type unmarshaler DocManifest200ResponsePagesItemCache
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DocManifest200ResponsePagesItemCache(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DocManifest200ResponsePagesItemCache) MarshalJSON() ([]byte, error) {
	type embed DocManifest200ResponsePagesItemCache
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DocManifest200ResponsePagesItemCache) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	docManifest200ResponsePagesItemStateFieldPageObjectNumber    = big.NewInt(1 << 0)
	docManifest200ResponsePagesItemStateFieldRevision            = big.NewInt(1 << 1)
	docManifest200ResponsePagesItemStateFieldWeakAnnotationState = big.NewInt(1 << 2)
)

type DocManifest200ResponsePagesItemState struct {
	PageObjectNumber    int                                                      `json:"pageObjectNumber" url:"pageObjectNumber"`
	Revision            *DocManifest200ResponsePagesItemStateRevision            `json:"revision" url:"revision"`
	WeakAnnotationState *DocManifest200ResponsePagesItemStateWeakAnnotationState `json:"weakAnnotationState" url:"weakAnnotationState"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DocManifest200ResponsePagesItemState) GetPageObjectNumber() int {
	if d == nil {
		return 0
	}
	return d.PageObjectNumber
}

func (d *DocManifest200ResponsePagesItemState) GetRevision() *DocManifest200ResponsePagesItemStateRevision {
	if d == nil {
		return nil
	}
	return d.Revision
}

func (d *DocManifest200ResponsePagesItemState) GetWeakAnnotationState() *DocManifest200ResponsePagesItemStateWeakAnnotationState {
	if d == nil {
		return nil
	}
	return d.WeakAnnotationState
}

func (d *DocManifest200ResponsePagesItemState) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DocManifest200ResponsePagesItemState) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetPageObjectNumber sets the PageObjectNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200ResponsePagesItemState) SetPageObjectNumber(pageObjectNumber int) {
	d.PageObjectNumber = pageObjectNumber
	d.require(docManifest200ResponsePagesItemStateFieldPageObjectNumber)
}

// SetRevision sets the Revision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200ResponsePagesItemState) SetRevision(revision *DocManifest200ResponsePagesItemStateRevision) {
	d.Revision = revision
	d.require(docManifest200ResponsePagesItemStateFieldRevision)
}

// SetWeakAnnotationState sets the WeakAnnotationState field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200ResponsePagesItemState) SetWeakAnnotationState(weakAnnotationState *DocManifest200ResponsePagesItemStateWeakAnnotationState) {
	d.WeakAnnotationState = weakAnnotationState
	d.require(docManifest200ResponsePagesItemStateFieldWeakAnnotationState)
}

func (d *DocManifest200ResponsePagesItemState) UnmarshalJSON(data []byte) error {
	type unmarshaler DocManifest200ResponsePagesItemState
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DocManifest200ResponsePagesItemState(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DocManifest200ResponsePagesItemState) MarshalJSON() ([]byte, error) {
	type embed DocManifest200ResponsePagesItemState
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DocManifest200ResponsePagesItemState) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	docManifest200ResponsePagesItemStateRevisionFieldDocSessionID     = big.NewInt(1 << 0)
	docManifest200ResponsePagesItemStateRevisionFieldPageObjectNumber = big.NewInt(1 << 1)
	docManifest200ResponsePagesItemStateRevisionFieldGeneration       = big.NewInt(1 << 2)
)

type DocManifest200ResponsePagesItemStateRevision struct {
	DocSessionID     string `json:"docSessionId" url:"docSessionId"`
	PageObjectNumber int    `json:"pageObjectNumber" url:"pageObjectNumber"`
	Generation       int    `json:"generation" url:"generation"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DocManifest200ResponsePagesItemStateRevision) GetDocSessionID() string {
	if d == nil {
		return ""
	}
	return d.DocSessionID
}

func (d *DocManifest200ResponsePagesItemStateRevision) GetPageObjectNumber() int {
	if d == nil {
		return 0
	}
	return d.PageObjectNumber
}

func (d *DocManifest200ResponsePagesItemStateRevision) GetGeneration() int {
	if d == nil {
		return 0
	}
	return d.Generation
}

func (d *DocManifest200ResponsePagesItemStateRevision) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DocManifest200ResponsePagesItemStateRevision) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetDocSessionID sets the DocSessionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200ResponsePagesItemStateRevision) SetDocSessionID(docSessionID string) {
	d.DocSessionID = docSessionID
	d.require(docManifest200ResponsePagesItemStateRevisionFieldDocSessionID)
}

// SetPageObjectNumber sets the PageObjectNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200ResponsePagesItemStateRevision) SetPageObjectNumber(pageObjectNumber int) {
	d.PageObjectNumber = pageObjectNumber
	d.require(docManifest200ResponsePagesItemStateRevisionFieldPageObjectNumber)
}

// SetGeneration sets the Generation field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200ResponsePagesItemStateRevision) SetGeneration(generation int) {
	d.Generation = generation
	d.require(docManifest200ResponsePagesItemStateRevisionFieldGeneration)
}

func (d *DocManifest200ResponsePagesItemStateRevision) UnmarshalJSON(data []byte) error {
	type unmarshaler DocManifest200ResponsePagesItemStateRevision
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DocManifest200ResponsePagesItemStateRevision(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DocManifest200ResponsePagesItemStateRevision) MarshalJSON() ([]byte, error) {
	type embed DocManifest200ResponsePagesItemStateRevision
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DocManifest200ResponsePagesItemStateRevision) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DocManifest200ResponsePagesItemStateWeakAnnotationState struct {
	Kind    string
	Unknown *DocManifest200ResponsePagesItemStateWeakAnnotationStateUnknown
	Known   *DocManifest200ResponsePagesItemStateWeakAnnotationStateKnown

	rawJSON json.RawMessage
}

func (d *DocManifest200ResponsePagesItemStateWeakAnnotationState) GetKind() string {
	if d == nil {
		return ""
	}
	return d.Kind
}

func (d *DocManifest200ResponsePagesItemStateWeakAnnotationState) GetUnknown() *DocManifest200ResponsePagesItemStateWeakAnnotationStateUnknown {
	if d == nil {
		return nil
	}
	return d.Unknown
}

func (d *DocManifest200ResponsePagesItemStateWeakAnnotationState) GetKnown() *DocManifest200ResponsePagesItemStateWeakAnnotationStateKnown {
	if d == nil {
		return nil
	}
	return d.Known
}

func (d *DocManifest200ResponsePagesItemStateWeakAnnotationState) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Kind string `json:"kind"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	d.Kind = unmarshaler.Kind
	if unmarshaler.Kind == "" {
		return fmt.Errorf("%T did not include discriminant kind", d)
	}
	switch unmarshaler.Kind {
	case "unknown":
		value := new(DocManifest200ResponsePagesItemStateWeakAnnotationStateUnknown)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		d.Unknown = value
	case "known":
		value := new(DocManifest200ResponsePagesItemStateWeakAnnotationStateKnown)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		d.Known = value
	}
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d DocManifest200ResponsePagesItemStateWeakAnnotationState) MarshalJSON() ([]byte, error) {
	if err := d.validate(); err != nil {
		return nil, err
	}
	if d.Unknown != nil {
		return internal.MarshalJSONWithExtraProperty(d.Unknown, "kind", "unknown")
	}
	if d.Known != nil {
		return internal.MarshalJSONWithExtraProperty(d.Known, "kind", "known")
	}
	if len(d.rawJSON) > 0 {
		return d.rawJSON, nil
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", d)
}

type DocManifest200ResponsePagesItemStateWeakAnnotationStateVisitor interface {
	VisitUnknown(*DocManifest200ResponsePagesItemStateWeakAnnotationStateUnknown) error
	VisitKnown(*DocManifest200ResponsePagesItemStateWeakAnnotationStateKnown) error
}

func (d *DocManifest200ResponsePagesItemStateWeakAnnotationState) Accept(visitor DocManifest200ResponsePagesItemStateWeakAnnotationStateVisitor) error {
	if d.Unknown != nil {
		return visitor.VisitUnknown(d.Unknown)
	}
	if d.Known != nil {
		return visitor.VisitKnown(d.Known)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", d)
}

func (d *DocManifest200ResponsePagesItemStateWeakAnnotationState) validate() error {
	if d == nil {
		return fmt.Errorf("type %T is nil", d)
	}
	var fields []string
	if d.Unknown != nil {
		fields = append(fields, "unknown")
	}
	if d.Known != nil {
		fields = append(fields, "known")
	}
	if len(fields) == 0 {
		if d.Kind != "" {
			if len(d.rawJSON) > 0 {
				return nil
			}
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", d, d.Kind)
		}
		return fmt.Errorf("type %T is empty", d)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", d, fields)
	}
	if d.Kind != "" {
		field := fields[0]
		if d.Kind != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				d,
				d.Kind,
				d,
			)
		}
	}
	return nil
}

var (
	docManifest200ResponsePagesItemStateWeakAnnotationStateKnownFieldHasAnyWeakAnnotations = big.NewInt(1 << 0)
)

type DocManifest200ResponsePagesItemStateWeakAnnotationStateKnown struct {
	HasAnyWeakAnnotations bool `json:"hasAnyWeakAnnotations" url:"hasAnyWeakAnnotations"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DocManifest200ResponsePagesItemStateWeakAnnotationStateKnown) GetHasAnyWeakAnnotations() bool {
	if d == nil {
		return false
	}
	return d.HasAnyWeakAnnotations
}

func (d *DocManifest200ResponsePagesItemStateWeakAnnotationStateKnown) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DocManifest200ResponsePagesItemStateWeakAnnotationStateKnown) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetHasAnyWeakAnnotations sets the HasAnyWeakAnnotations field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200ResponsePagesItemStateWeakAnnotationStateKnown) SetHasAnyWeakAnnotations(hasAnyWeakAnnotations bool) {
	d.HasAnyWeakAnnotations = hasAnyWeakAnnotations
	d.require(docManifest200ResponsePagesItemStateWeakAnnotationStateKnownFieldHasAnyWeakAnnotations)
}

func (d *DocManifest200ResponsePagesItemStateWeakAnnotationStateKnown) UnmarshalJSON(data []byte) error {
	type unmarshaler DocManifest200ResponsePagesItemStateWeakAnnotationStateKnown
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DocManifest200ResponsePagesItemStateWeakAnnotationStateKnown(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DocManifest200ResponsePagesItemStateWeakAnnotationStateKnown) MarshalJSON() ([]byte, error) {
	type embed DocManifest200ResponsePagesItemStateWeakAnnotationStateKnown
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DocManifest200ResponsePagesItemStateWeakAnnotationStateKnown) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DocManifest200ResponsePagesItemStateWeakAnnotationStateUnknown struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DocManifest200ResponsePagesItemStateWeakAnnotationStateUnknown) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DocManifest200ResponsePagesItemStateWeakAnnotationStateUnknown) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

func (d *DocManifest200ResponsePagesItemStateWeakAnnotationStateUnknown) UnmarshalJSON(data []byte) error {
	type unmarshaler DocManifest200ResponsePagesItemStateWeakAnnotationStateUnknown
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DocManifest200ResponsePagesItemStateWeakAnnotationStateUnknown(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DocManifest200ResponsePagesItemStateWeakAnnotationStateUnknown) MarshalJSON() ([]byte, error) {
	type embed DocManifest200ResponsePagesItemStateWeakAnnotationStateUnknown
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DocManifest200ResponsePagesItemStateWeakAnnotationStateUnknown) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	docManifest200ResponseScopesFieldContent     = big.NewInt(1 << 0)
	docManifest200ResponseScopesFieldAnnotations = big.NewInt(1 << 1)
	docManifest200ResponseScopesFieldLayout      = big.NewInt(1 << 2)
	docManifest200ResponseScopesFieldAttachments = big.NewInt(1 << 3)
	docManifest200ResponseScopesFieldMetadata    = big.NewInt(1 << 4)
	docManifest200ResponseScopesFieldActions     = big.NewInt(1 << 5)
)

type DocManifest200ResponseScopes struct {
	Content     DocManifest200ResponseScopesContent     `json:"content" url:"content"`
	Annotations DocManifest200ResponseScopesAnnotations `json:"annotations" url:"annotations"`
	Layout      DocManifest200ResponseScopesLayout      `json:"layout" url:"layout"`
	Attachments DocManifest200ResponseScopesAttachments `json:"attachments" url:"attachments"`
	Metadata    DocManifest200ResponseScopesMetadata    `json:"metadata" url:"metadata"`
	Actions     DocManifest200ResponseScopesActions     `json:"actions" url:"actions"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DocManifest200ResponseScopes) GetContent() DocManifest200ResponseScopesContent {
	if d == nil {
		return ""
	}
	return d.Content
}

func (d *DocManifest200ResponseScopes) GetAnnotations() DocManifest200ResponseScopesAnnotations {
	if d == nil {
		return ""
	}
	return d.Annotations
}

func (d *DocManifest200ResponseScopes) GetLayout() DocManifest200ResponseScopesLayout {
	if d == nil {
		return ""
	}
	return d.Layout
}

func (d *DocManifest200ResponseScopes) GetAttachments() DocManifest200ResponseScopesAttachments {
	if d == nil {
		return ""
	}
	return d.Attachments
}

func (d *DocManifest200ResponseScopes) GetMetadata() DocManifest200ResponseScopesMetadata {
	if d == nil {
		return ""
	}
	return d.Metadata
}

func (d *DocManifest200ResponseScopes) GetActions() DocManifest200ResponseScopesActions {
	if d == nil {
		return ""
	}
	return d.Actions
}

func (d *DocManifest200ResponseScopes) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DocManifest200ResponseScopes) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetContent sets the Content field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200ResponseScopes) SetContent(content DocManifest200ResponseScopesContent) {
	d.Content = content
	d.require(docManifest200ResponseScopesFieldContent)
}

// SetAnnotations sets the Annotations field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200ResponseScopes) SetAnnotations(annotations DocManifest200ResponseScopesAnnotations) {
	d.Annotations = annotations
	d.require(docManifest200ResponseScopesFieldAnnotations)
}

// SetLayout sets the Layout field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200ResponseScopes) SetLayout(layout DocManifest200ResponseScopesLayout) {
	d.Layout = layout
	d.require(docManifest200ResponseScopesFieldLayout)
}

// SetAttachments sets the Attachments field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200ResponseScopes) SetAttachments(attachments DocManifest200ResponseScopesAttachments) {
	d.Attachments = attachments
	d.require(docManifest200ResponseScopesFieldAttachments)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200ResponseScopes) SetMetadata(metadata DocManifest200ResponseScopesMetadata) {
	d.Metadata = metadata
	d.require(docManifest200ResponseScopesFieldMetadata)
}

// SetActions sets the Actions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocManifest200ResponseScopes) SetActions(actions DocManifest200ResponseScopesActions) {
	d.Actions = actions
	d.require(docManifest200ResponseScopesFieldActions)
}

func (d *DocManifest200ResponseScopes) UnmarshalJSON(data []byte) error {
	type unmarshaler DocManifest200ResponseScopes
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DocManifest200ResponseScopes(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DocManifest200ResponseScopes) MarshalJSON() ([]byte, error) {
	type embed DocManifest200ResponseScopes
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DocManifest200ResponseScopes) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DocManifest200ResponseScopesActions string

const (
	DocManifest200ResponseScopesActionsBase  DocManifest200ResponseScopesActions = "base"
	DocManifest200ResponseScopesActionsLayer DocManifest200ResponseScopesActions = "layer"
)

func NewDocManifest200ResponseScopesActionsFromString(s string) (DocManifest200ResponseScopesActions, error) {
	switch s {
	case "base":
		return DocManifest200ResponseScopesActionsBase, nil
	case "layer":
		return DocManifest200ResponseScopesActionsLayer, nil
	}
	var t DocManifest200ResponseScopesActions
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DocManifest200ResponseScopesActions) Ptr() *DocManifest200ResponseScopesActions {
	return &d
}

type DocManifest200ResponseScopesAnnotations string

const (
	DocManifest200ResponseScopesAnnotationsBase  DocManifest200ResponseScopesAnnotations = "base"
	DocManifest200ResponseScopesAnnotationsLayer DocManifest200ResponseScopesAnnotations = "layer"
)

func NewDocManifest200ResponseScopesAnnotationsFromString(s string) (DocManifest200ResponseScopesAnnotations, error) {
	switch s {
	case "base":
		return DocManifest200ResponseScopesAnnotationsBase, nil
	case "layer":
		return DocManifest200ResponseScopesAnnotationsLayer, nil
	}
	var t DocManifest200ResponseScopesAnnotations
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DocManifest200ResponseScopesAnnotations) Ptr() *DocManifest200ResponseScopesAnnotations {
	return &d
}

type DocManifest200ResponseScopesAttachments string

const (
	DocManifest200ResponseScopesAttachmentsBase  DocManifest200ResponseScopesAttachments = "base"
	DocManifest200ResponseScopesAttachmentsLayer DocManifest200ResponseScopesAttachments = "layer"
)

func NewDocManifest200ResponseScopesAttachmentsFromString(s string) (DocManifest200ResponseScopesAttachments, error) {
	switch s {
	case "base":
		return DocManifest200ResponseScopesAttachmentsBase, nil
	case "layer":
		return DocManifest200ResponseScopesAttachmentsLayer, nil
	}
	var t DocManifest200ResponseScopesAttachments
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DocManifest200ResponseScopesAttachments) Ptr() *DocManifest200ResponseScopesAttachments {
	return &d
}

type DocManifest200ResponseScopesContent string

const (
	DocManifest200ResponseScopesContentBase  DocManifest200ResponseScopesContent = "base"
	DocManifest200ResponseScopesContentLayer DocManifest200ResponseScopesContent = "layer"
)

func NewDocManifest200ResponseScopesContentFromString(s string) (DocManifest200ResponseScopesContent, error) {
	switch s {
	case "base":
		return DocManifest200ResponseScopesContentBase, nil
	case "layer":
		return DocManifest200ResponseScopesContentLayer, nil
	}
	var t DocManifest200ResponseScopesContent
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DocManifest200ResponseScopesContent) Ptr() *DocManifest200ResponseScopesContent {
	return &d
}

type DocManifest200ResponseScopesLayout string

const (
	DocManifest200ResponseScopesLayoutBase  DocManifest200ResponseScopesLayout = "base"
	DocManifest200ResponseScopesLayoutLayer DocManifest200ResponseScopesLayout = "layer"
)

func NewDocManifest200ResponseScopesLayoutFromString(s string) (DocManifest200ResponseScopesLayout, error) {
	switch s {
	case "base":
		return DocManifest200ResponseScopesLayoutBase, nil
	case "layer":
		return DocManifest200ResponseScopesLayoutLayer, nil
	}
	var t DocManifest200ResponseScopesLayout
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DocManifest200ResponseScopesLayout) Ptr() *DocManifest200ResponseScopesLayout {
	return &d
}

type DocManifest200ResponseScopesMetadata string

const (
	DocManifest200ResponseScopesMetadataBase  DocManifest200ResponseScopesMetadata = "base"
	DocManifest200ResponseScopesMetadataLayer DocManifest200ResponseScopesMetadata = "layer"
)

func NewDocManifest200ResponseScopesMetadataFromString(s string) (DocManifest200ResponseScopesMetadata, error) {
	switch s {
	case "base":
		return DocManifest200ResponseScopesMetadataBase, nil
	case "layer":
		return DocManifest200ResponseScopesMetadataLayer, nil
	}
	var t DocManifest200ResponseScopesMetadata
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DocManifest200ResponseScopesMetadata) Ptr() *DocManifest200ResponseScopesMetadata {
	return &d
}

var (
	docText200ResponseFieldText      = big.NewInt(1 << 0)
	docText200ResponseFieldCharCount = big.NewInt(1 << 1)
	docText200ResponseFieldCharMap   = big.NewInt(1 << 2)
)

type DocText200Response struct {
	Text      string  `json:"text" url:"text"`
	CharCount int     `json:"charCount" url:"charCount"`
	CharMap   [][]any `json:"charMap,omitempty" url:"charMap,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DocText200Response) GetText() string {
	if d == nil {
		return ""
	}
	return d.Text
}

func (d *DocText200Response) GetCharCount() int {
	if d == nil {
		return 0
	}
	return d.CharCount
}

func (d *DocText200Response) GetCharMap() [][]any {
	if d == nil {
		return nil
	}
	return d.CharMap
}

func (d *DocText200Response) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DocText200Response) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetText sets the Text field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocText200Response) SetText(text string) {
	d.Text = text
	d.require(docText200ResponseFieldText)
}

// SetCharCount sets the CharCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocText200Response) SetCharCount(charCount int) {
	d.CharCount = charCount
	d.require(docText200ResponseFieldCharCount)
}

// SetCharMap sets the CharMap field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocText200Response) SetCharMap(charMap [][]any) {
	d.CharMap = charMap
	d.require(docText200ResponseFieldCharMap)
}

func (d *DocText200Response) UnmarshalJSON(data []byte) error {
	type unmarshaler DocText200Response
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DocText200Response(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DocText200Response) MarshalJSON() ([]byte, error) {
	type embed DocText200Response
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DocText200Response) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}
