// Code generated by Fern. DO NOT EDIT.

package cloudpdf

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersIssueTokensRequest(t *testing.T) {
	t.Run("SetTenantID", func(t *testing.T) {
		obj := &IssueTokensRequest{}
		var fernTestValueTenantID string
		obj.SetTenantID(fernTestValueTenantID)
		assert.Equal(t, fernTestValueTenantID, obj.TenantID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitIssueTokensRequest(t *testing.T) {
	t.Run("SetTenantID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &IssueTokensRequest{}
		var fernTestValueTenantID string

		// Act
		obj.SetTenantID(fernTestValueTenantID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersTokensRevokeRequest(t *testing.T) {
	t.Run("SetTenantID", func(t *testing.T) {
		obj := &TokensRevokeRequest{}
		var fernTestValueTenantID string
		obj.SetTenantID(fernTestValueTenantID)
		assert.Equal(t, fernTestValueTenantID, obj.TenantID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetJti", func(t *testing.T) {
		obj := &TokensRevokeRequest{}
		var fernTestValueJti string
		obj.SetJti(fernTestValueJti)
		assert.Equal(t, fernTestValueJti, obj.Jti)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetReason", func(t *testing.T) {
		obj := &TokensRevokeRequest{}
		var fernTestValueReason *string
		obj.SetReason(fernTestValueReason)
		assert.Equal(t, fernTestValueReason, obj.Reason)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExpiresAtSeconds", func(t *testing.T) {
		obj := &TokensRevokeRequest{}
		var fernTestValueExpiresAtSeconds *int
		obj.SetExpiresAtSeconds(fernTestValueExpiresAtSeconds)
		assert.Equal(t, fernTestValueExpiresAtSeconds, obj.ExpiresAtSeconds)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitTokensRevokeRequest(t *testing.T) {
	t.Run("SetTenantID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensRevokeRequest{}
		var fernTestValueTenantID string

		// Act
		obj.SetTenantID(fernTestValueTenantID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetJti_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensRevokeRequest{}
		var fernTestValueJti string

		// Act
		obj.SetJti(fernTestValueJti)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetReason_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensRevokeRequest{}
		var fernTestValueReason *string

		// Act
		obj.SetReason(fernTestValueReason)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExpiresAtSeconds_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensRevokeRequest{}
		var fernTestValueExpiresAtSeconds *int

		// Act
		obj.SetExpiresAtSeconds(fernTestValueExpiresAtSeconds)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersTokensIssue200Response(t *testing.T) {
	t.Run("SetToken", func(t *testing.T) {
		obj := &TokensIssue200Response{}
		var fernTestValueToken string
		obj.SetToken(fernTestValueToken)
		assert.Equal(t, fernTestValueToken, obj.Token)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetJti", func(t *testing.T) {
		obj := &TokensIssue200Response{}
		var fernTestValueJti string
		obj.SetJti(fernTestValueJti)
		assert.Equal(t, fernTestValueJti, obj.Jti)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExpiresAt", func(t *testing.T) {
		obj := &TokensIssue200Response{}
		var fernTestValueExpiresAt float64
		obj.SetExpiresAt(fernTestValueExpiresAt)
		assert.Equal(t, fernTestValueExpiresAt, obj.ExpiresAt)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersTokensIssue200Response(t *testing.T) {
	t.Run("GetToken", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssue200Response{}
		var expected string
		obj.Token = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetToken(), "getter should return the property value")
	})

	t.Run("GetToken_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssue200Response
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetToken() // Should return zero value
	})

	t.Run("GetJti", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssue200Response{}
		var expected string
		obj.Jti = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetJti(), "getter should return the property value")
	})

	t.Run("GetJti_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssue200Response
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetJti() // Should return zero value
	})

	t.Run("GetExpiresAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssue200Response{}
		var expected float64
		obj.ExpiresAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetExpiresAt(), "getter should return the property value")
	})

	t.Run("GetExpiresAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssue200Response
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetExpiresAt() // Should return zero value
	})

}

func TestSettersMarkExplicitTokensIssue200Response(t *testing.T) {
	t.Run("SetToken_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssue200Response{}
		var fernTestValueToken string

		// Act
		obj.SetToken(fernTestValueToken)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetJti_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssue200Response{}
		var fernTestValueJti string

		// Act
		obj.SetJti(fernTestValueJti)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExpiresAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssue200Response{}
		var fernTestValueExpiresAt float64

		// Act
		obj.SetExpiresAt(fernTestValueExpiresAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestGettersTokensIssueRequest(t *testing.T) {
	t.Run("GetKind", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequest{}
		var expected string
		obj.Kind = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetKind(), "getter should return the property value")
	})

	t.Run("GetKind_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequest
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetKind() // Should return zero value
	})

	t.Run("GetDoc", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequest{}
		var expected *TokensIssueRequestDoc
		obj.Doc = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDoc(), "getter should return the property value")
	})

	t.Run("GetDoc_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequest{}
		obj.Doc = nil

		// Act & Assert
		assert.Nil(t, obj.GetDoc(), "getter should return nil when property is nil")
	})

	t.Run("GetDoc_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequest
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDoc() // Should return zero value
	})

	t.Run("GetTenant", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequest{}
		var expected *TokensIssueRequestTenant
		obj.Tenant = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTenant(), "getter should return the property value")
	})

	t.Run("GetTenant_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequest{}
		obj.Tenant = nil

		// Act & Assert
		assert.Nil(t, obj.GetTenant(), "getter should return nil when property is nil")
	})

	t.Run("GetTenant_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequest
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTenant() // Should return zero value
	})

}

func TestSettersTokensIssueRequestDoc(t *testing.T) {
	t.Run("SetSub", func(t *testing.T) {
		obj := &TokensIssueRequestDoc{}
		var fernTestValueSub string
		obj.SetSub(fernTestValueSub)
		assert.Equal(t, fernTestValueSub, obj.Sub)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDocID", func(t *testing.T) {
		obj := &TokensIssueRequestDoc{}
		var fernTestValueDocID string
		obj.SetDocID(fernTestValueDocID)
		assert.Equal(t, fernTestValueDocID, obj.DocID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLayerName", func(t *testing.T) {
		obj := &TokensIssueRequestDoc{}
		var fernTestValueLayerName *string
		obj.SetLayerName(fernTestValueLayerName)
		assert.Equal(t, fernTestValueLayerName, obj.LayerName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetScope", func(t *testing.T) {
		obj := &TokensIssueRequestDoc{}
		var fernTestValueScope []string
		obj.SetScope(fernTestValueScope)
		assert.Equal(t, fernTestValueScope, obj.Scope)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUserID", func(t *testing.T) {
		obj := &TokensIssueRequestDoc{}
		var fernTestValueUserID *string
		obj.SetUserID(fernTestValueUserID)
		assert.Equal(t, fernTestValueUserID, obj.UserID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDisplayName", func(t *testing.T) {
		obj := &TokensIssueRequestDoc{}
		var fernTestValueDisplayName *string
		obj.SetDisplayName(fernTestValueDisplayName)
		assert.Equal(t, fernTestValueDisplayName, obj.DisplayName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetGroupID", func(t *testing.T) {
		obj := &TokensIssueRequestDoc{}
		var fernTestValueGroupID *string
		obj.SetGroupID(fernTestValueGroupID)
		assert.Equal(t, fernTestValueGroupID, obj.GroupID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetGroups", func(t *testing.T) {
		obj := &TokensIssueRequestDoc{}
		var fernTestValueGroups []string
		obj.SetGroups(fernTestValueGroups)
		assert.Equal(t, fernTestValueGroups, obj.Groups)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOrigins", func(t *testing.T) {
		obj := &TokensIssueRequestDoc{}
		var fernTestValueOrigins []string
		obj.SetOrigins(fernTestValueOrigins)
		assert.Equal(t, fernTestValueOrigins, obj.Origins)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExpiresIn", func(t *testing.T) {
		obj := &TokensIssueRequestDoc{}
		var fernTestValueExpiresIn int
		obj.SetExpiresIn(fernTestValueExpiresIn)
		assert.Equal(t, fernTestValueExpiresIn, obj.ExpiresIn)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersTokensIssueRequestDoc(t *testing.T) {
	t.Run("GetSub", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var expected string
		obj.Sub = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSub(), "getter should return the property value")
	})

	t.Run("GetSub_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestDoc
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSub() // Should return zero value
	})

	t.Run("GetDocID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var expected string
		obj.DocID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDocID(), "getter should return the property value")
	})

	t.Run("GetDocID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestDoc
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDocID() // Should return zero value
	})

	t.Run("GetLayerName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var expected *string
		obj.LayerName = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLayerName(), "getter should return the property value")
	})

	t.Run("GetLayerName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		obj.LayerName = nil

		// Act & Assert
		assert.Nil(t, obj.GetLayerName(), "getter should return nil when property is nil")
	})

	t.Run("GetLayerName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestDoc
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLayerName() // Should return zero value
	})

	t.Run("GetScope", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var expected []string
		obj.Scope = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetScope(), "getter should return the property value")
	})

	t.Run("GetScope_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		obj.Scope = nil

		// Act & Assert
		assert.Nil(t, obj.GetScope(), "getter should return nil when property is nil")
	})

	t.Run("GetScope_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestDoc
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetScope() // Should return zero value
	})

	t.Run("GetUserID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var expected *string
		obj.UserID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUserID(), "getter should return the property value")
	})

	t.Run("GetUserID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		obj.UserID = nil

		// Act & Assert
		assert.Nil(t, obj.GetUserID(), "getter should return nil when property is nil")
	})

	t.Run("GetUserID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestDoc
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUserID() // Should return zero value
	})

	t.Run("GetDisplayName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var expected *string
		obj.DisplayName = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDisplayName(), "getter should return the property value")
	})

	t.Run("GetDisplayName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		obj.DisplayName = nil

		// Act & Assert
		assert.Nil(t, obj.GetDisplayName(), "getter should return nil when property is nil")
	})

	t.Run("GetDisplayName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestDoc
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDisplayName() // Should return zero value
	})

	t.Run("GetGroupID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var expected *string
		obj.GroupID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetGroupID(), "getter should return the property value")
	})

	t.Run("GetGroupID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		obj.GroupID = nil

		// Act & Assert
		assert.Nil(t, obj.GetGroupID(), "getter should return nil when property is nil")
	})

	t.Run("GetGroupID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestDoc
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetGroupID() // Should return zero value
	})

	t.Run("GetGroups", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var expected []string
		obj.Groups = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetGroups(), "getter should return the property value")
	})

	t.Run("GetGroups_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		obj.Groups = nil

		// Act & Assert
		assert.Nil(t, obj.GetGroups(), "getter should return nil when property is nil")
	})

	t.Run("GetGroups_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestDoc
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetGroups() // Should return zero value
	})

	t.Run("GetOrigins", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var expected []string
		obj.Origins = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOrigins(), "getter should return the property value")
	})

	t.Run("GetOrigins_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		obj.Origins = nil

		// Act & Assert
		assert.Nil(t, obj.GetOrigins(), "getter should return nil when property is nil")
	})

	t.Run("GetOrigins_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestDoc
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOrigins() // Should return zero value
	})

	t.Run("GetExpiresIn", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var expected int
		obj.ExpiresIn = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetExpiresIn(), "getter should return the property value")
	})

	t.Run("GetExpiresIn_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestDoc
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetExpiresIn() // Should return zero value
	})

}

func TestSettersMarkExplicitTokensIssueRequestDoc(t *testing.T) {
	t.Run("SetSub_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var fernTestValueSub string

		// Act
		obj.SetSub(fernTestValueSub)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDocID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var fernTestValueDocID string

		// Act
		obj.SetDocID(fernTestValueDocID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLayerName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var fernTestValueLayerName *string

		// Act
		obj.SetLayerName(fernTestValueLayerName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetScope_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var fernTestValueScope []string

		// Act
		obj.SetScope(fernTestValueScope)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUserID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var fernTestValueUserID *string

		// Act
		obj.SetUserID(fernTestValueUserID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDisplayName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var fernTestValueDisplayName *string

		// Act
		obj.SetDisplayName(fernTestValueDisplayName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetGroupID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var fernTestValueGroupID *string

		// Act
		obj.SetGroupID(fernTestValueGroupID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetGroups_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var fernTestValueGroups []string

		// Act
		obj.SetGroups(fernTestValueGroups)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOrigins_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var fernTestValueOrigins []string

		// Act
		obj.SetOrigins(fernTestValueOrigins)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExpiresIn_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}
		var fernTestValueExpiresIn int

		// Act
		obj.SetExpiresIn(fernTestValueExpiresIn)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersTokensIssueRequestTenant(t *testing.T) {
	t.Run("SetSub", func(t *testing.T) {
		obj := &TokensIssueRequestTenant{}
		var fernTestValueSub string
		obj.SetSub(fernTestValueSub)
		assert.Equal(t, fernTestValueSub, obj.Sub)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetScope", func(t *testing.T) {
		obj := &TokensIssueRequestTenant{}
		var fernTestValueScope []*TokensIssueRequestTenantScopeItem
		obj.SetScope(fernTestValueScope)
		assert.Equal(t, fernTestValueScope, obj.Scope)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExpiresIn", func(t *testing.T) {
		obj := &TokensIssueRequestTenant{}
		var fernTestValueExpiresIn int
		obj.SetExpiresIn(fernTestValueExpiresIn)
		assert.Equal(t, fernTestValueExpiresIn, obj.ExpiresIn)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersTokensIssueRequestTenant(t *testing.T) {
	t.Run("GetSub", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestTenant{}
		var expected string
		obj.Sub = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSub(), "getter should return the property value")
	})

	t.Run("GetSub_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestTenant
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSub() // Should return zero value
	})

	t.Run("GetScope", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestTenant{}
		var expected []*TokensIssueRequestTenantScopeItem
		obj.Scope = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetScope(), "getter should return the property value")
	})

	t.Run("GetScope_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestTenant{}
		obj.Scope = nil

		// Act & Assert
		assert.Nil(t, obj.GetScope(), "getter should return nil when property is nil")
	})

	t.Run("GetScope_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestTenant
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetScope() // Should return zero value
	})

	t.Run("GetExpiresIn", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestTenant{}
		var expected int
		obj.ExpiresIn = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetExpiresIn(), "getter should return the property value")
	})

	t.Run("GetExpiresIn_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestTenant
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetExpiresIn() // Should return zero value
	})

}

func TestSettersMarkExplicitTokensIssueRequestTenant(t *testing.T) {
	t.Run("SetSub_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestTenant{}
		var fernTestValueSub string

		// Act
		obj.SetSub(fernTestValueSub)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetScope_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestTenant{}
		var fernTestValueScope []*TokensIssueRequestTenantScopeItem

		// Act
		obj.SetScope(fernTestValueScope)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExpiresIn_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestTenant{}
		var fernTestValueExpiresIn int

		// Act
		obj.SetExpiresIn(fernTestValueExpiresIn)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestGettersTokensIssueRequestTenantScopeItem(t *testing.T) {
	t.Run("GetTokensIssueRequestTenantScopeItemZero", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestTenantScopeItem{}
		var expected TokensIssueRequestTenantScopeItemZero
		obj.TokensIssueRequestTenantScopeItemZero = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTokensIssueRequestTenantScopeItemZero(), "getter should return the property value")
	})

	t.Run("GetTokensIssueRequestTenantScopeItemZero_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestTenantScopeItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTokensIssueRequestTenantScopeItemZero() // Should return zero value
	})

	t.Run("GetTokensIssueRequestTenantScopeItemOne", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestTenantScopeItem{}
		var expected TokensIssueRequestTenantScopeItemOne
		obj.TokensIssueRequestTenantScopeItemOne = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTokensIssueRequestTenantScopeItemOne(), "getter should return the property value")
	})

	t.Run("GetTokensIssueRequestTenantScopeItemOne_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestTenantScopeItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTokensIssueRequestTenantScopeItemOne() // Should return zero value
	})

}

func TestJSONMarshalingTokensIssue200Response(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssue200Response{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled TokensIssue200Response
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj TokensIssue200Response
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj TokensIssue200Response
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingTokensIssueRequestDoc(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestDoc{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled TokensIssueRequestDoc
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj TokensIssueRequestDoc
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj TokensIssueRequestDoc
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingTokensIssueRequestTenant(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TokensIssueRequestTenant{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled TokensIssueRequestTenant
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj TokensIssueRequestTenant
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj TokensIssueRequestTenant
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringTokensIssue200Response(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &TokensIssue200Response{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssue200Response
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringTokensIssueRequestDoc(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &TokensIssueRequestDoc{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestDoc
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringTokensIssueRequestTenant(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &TokensIssueRequestTenant{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestTenant
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumTokensIssueRequestTenantScopeItemOne(t *testing.T) {
	t.Run("NewFromString_docs_create", func(t *testing.T) {
		t.Parallel()
		val, err := NewTokensIssueRequestTenantScopeItemOneFromString("docs.create")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TokensIssueRequestTenantScopeItemOne("docs.create"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_docs_read", func(t *testing.T) {
		t.Parallel()
		val, err := NewTokensIssueRequestTenantScopeItemOneFromString("docs.read")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TokensIssueRequestTenantScopeItemOne("docs.read"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_docs_delete", func(t *testing.T) {
		t.Parallel()
		val, err := NewTokensIssueRequestTenantScopeItemOneFromString("docs.delete")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TokensIssueRequestTenantScopeItemOne("docs.delete"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_tokens_issue_doc", func(t *testing.T) {
		t.Parallel()
		val, err := NewTokensIssueRequestTenantScopeItemOneFromString("tokens.issue-doc")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TokensIssueRequestTenantScopeItemOne("tokens.issue-doc"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_tokens_revoke", func(t *testing.T) {
		t.Parallel()
		val, err := NewTokensIssueRequestTenantScopeItemOneFromString("tokens.revoke")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TokensIssueRequestTenantScopeItemOne("tokens.revoke"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_shares_manage", func(t *testing.T) {
		t.Parallel()
		val, err := NewTokensIssueRequestTenantScopeItemOneFromString("shares.manage")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TokensIssueRequestTenantScopeItemOne("shares.manage"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewTokensIssueRequestTenantScopeItemOneFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewTokensIssueRequestTenantScopeItemOneFromString("docs.create")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumTokensIssueRequestTenantScopeItemZero(t *testing.T) {
	t.Run("NewFromString_*", func(t *testing.T) {
		t.Parallel()
		val, err := NewTokensIssueRequestTenantScopeItemZeroFromString("*")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, TokensIssueRequestTenantScopeItemZero("*"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewTokensIssueRequestTenantScopeItemZeroFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewTokensIssueRequestTenantScopeItemZeroFromString("*")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesTokensIssue200Response(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &TokensIssue200Response{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssue200Response
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesTokensIssueRequestDoc(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &TokensIssueRequestDoc{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestDoc
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesTokensIssueRequestTenant(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &TokensIssueRequestTenant{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TokensIssueRequestTenant
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
