// Code generated by Fern. DO NOT EDIT.

package annotations

import (
	context "context"
	io "io"

	cloudpdf "github.com/embedpdf/cloudpdf-sdk-go/v3"
	core "github.com/embedpdf/cloudpdf-sdk-go/v3/core"
	doc "github.com/embedpdf/cloudpdf-sdk-go/v3/doc"
	internal "github.com/embedpdf/cloudpdf-sdk-go/v3/internal"
	option "github.com/embedpdf/cloudpdf-sdk-go/v3/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns one entry per page plus the audit-log cursor for reconciling subsequent document events. Page order is unspecified; join by `pageState.pageObjectNumber` when display order matters.
//
// Example:
//
//	request := &doc.ListAllAnnotationsRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	}
//	client.Doc.Annotations.ListAll(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListAll(
	ctx context.Context,
	request *doc.ListAllAnnotationsRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocAnnotationsListAll200Response, error) {
	response, err := c.WithRawResponse.ListAll(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &doc.ListAnnotationsRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Pon: 1,
//	}
//	client.Doc.Annotations.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *doc.ListAnnotationsRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocAnnotationsList200Response, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Doc JWTs may instead carry collab scopes (annotations:create:self, …) that refine per-annotation authorship rules; the API token is exempt from both.
//
// Example:
//
//	request := &doc.CreateAnnotationsRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Pon: 1,
//	    Body: map[string]any{
//	        "key": "value",
//	    },
//	}
//	client.Doc.Annotations.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *doc.CreateAnnotationsRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocAnnotationsCreate200Response, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &doc.DeleteAnnotationsRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Pon: 1,
//	    AnnotKey: "annotKey",
//	}
//	client.Doc.Annotations.Delete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Delete(
	ctx context.Context,
	request *doc.DeleteAnnotationsRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocAnnotationsDelete200Response, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &doc.UpdateAnnotationsRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Pon: 1,
//	    AnnotKey: "annotKey",
//	    Body: map[string]any{
//	        "key": "value",
//	    },
//	}
//	client.Doc.Annotations.Update(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Update(
	ctx context.Context,
	request *doc.UpdateAnnotationsRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocAnnotationsUpdate200Response, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &doc.ExportAppearanceAnnotationsRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Pon: 1,
//	    Body: map[string]any{
//	        "string": map[string]any{
//	            "key": "value",
//	        },
//	    },
//	}
//	client.Doc.Annotations.ExportAppearance(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ExportAppearance(
	ctx context.Context,
	request *doc.ExportAppearanceAnnotationsRequest,
	opts ...option.RequestOption,
) (io.Reader, error) {
	response, err := c.WithRawResponse.ExportAppearance(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &doc.FlattenAnnotationsRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Pon: 1,
//	    Body: map[string]any{
//	        "key": "value",
//	    },
//	}
//	client.Doc.Annotations.Flatten(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Flatten(
	ctx context.Context,
	request *doc.FlattenAnnotationsRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocAnnotationsFlatten200Response, error) {
	response, err := c.WithRawResponse.Flatten(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
