// Code generated by Fern. DO NOT EDIT.

package doc

import (
	cloudpdf "github.com/embedpdf/cloudpdf-sdk-go/v3"
	core "github.com/embedpdf/cloudpdf-sdk-go/v3/core"
	internal "github.com/embedpdf/cloudpdf-sdk-go/v3/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	404: func(apiError *core.APIError) error {
		return &cloudpdf.NotFoundError{
			APIError: apiError,
		}
	},
	400: func(apiError *core.APIError) error {
		return &cloudpdf.BadRequestError{
			APIError: apiError,
		}
	},
}
