// Code generated by Fern. DO NOT EDIT.

package doc

import (
	json "encoding/json"
	fmt "fmt"
	v3 "github.com/embedpdf/cloudpdf-sdk-go/v3"
	big "math/big"
)

var (
	exportDataFormsRequestFieldDocumentPassword = big.NewInt(1 << 0)
	exportDataFormsRequestFieldDocID            = big.NewInt(1 << 1)
	exportDataFormsRequestFieldLayerName        = big.NewInt(1 << 2)
	exportDataFormsRequestFieldFormat           = big.NewInt(1 << 3)
)

type ExportDataFormsRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string                       `json:"-" url:"-"`
	DocID            string                        `json:"-" url:"-"`
	LayerName        string                        `json:"-" url:"-"`
	Format           *ExportDataFormsRequestFormat `json:"-" url:"format,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (e *ExportDataFormsRequest) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExportDataFormsRequest) SetDocumentPassword(documentPassword *string) {
	e.DocumentPassword = documentPassword
	e.require(exportDataFormsRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExportDataFormsRequest) SetDocID(docID string) {
	e.DocID = docID
	e.require(exportDataFormsRequestFieldDocID)
}

// SetLayerName sets the LayerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExportDataFormsRequest) SetLayerName(layerName string) {
	e.LayerName = layerName
	e.require(exportDataFormsRequestFieldLayerName)
}

// SetFormat sets the Format field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExportDataFormsRequest) SetFormat(format *ExportDataFormsRequestFormat) {
	e.Format = format
	e.require(exportDataFormsRequestFieldFormat)
}

var (
	getFormsRequestFieldDocumentPassword = big.NewInt(1 << 0)
	getFormsRequestFieldDocID            = big.NewInt(1 << 1)
	getFormsRequestFieldLayerName        = big.NewInt(1 << 2)
)

type GetFormsRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string `json:"-" url:"-"`
	DocID            string  `json:"-" url:"-"`
	LayerName        string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetFormsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFormsRequest) SetDocumentPassword(documentPassword *string) {
	g.DocumentPassword = documentPassword
	g.require(getFormsRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFormsRequest) SetDocID(docID string) {
	g.DocID = docID
	g.require(getFormsRequestFieldDocID)
}

// SetLayerName sets the LayerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFormsRequest) SetLayerName(layerName string) {
	g.LayerName = layerName
	g.require(getFormsRequestFieldLayerName)
}

var (
	importDataFormsRequestFieldDocumentPassword = big.NewInt(1 << 0)
	importDataFormsRequestFieldDocID            = big.NewInt(1 << 1)
	importDataFormsRequestFieldLayerName        = big.NewInt(1 << 2)
)

type ImportDataFormsRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string                      `json:"-" url:"-"`
	DocID            string                       `json:"-" url:"-"`
	LayerName        string                       `json:"-" url:"-"`
	Body             v3.DocFormsImportDataRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *ImportDataFormsRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportDataFormsRequest) SetDocumentPassword(documentPassword *string) {
	i.DocumentPassword = documentPassword
	i.require(importDataFormsRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportDataFormsRequest) SetDocID(docID string) {
	i.DocID = docID
	i.require(importDataFormsRequestFieldDocID)
}

// SetLayerName sets the LayerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportDataFormsRequest) SetLayerName(layerName string) {
	i.LayerName = layerName
	i.require(importDataFormsRequestFieldLayerName)
}

func (i *ImportDataFormsRequest) UnmarshalJSON(data []byte) error {
	var body v3.DocFormsImportDataRequest
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	i.Body = body
	return nil
}

func (i *ImportDataFormsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.Body)
}

var (
	resetFormsRequestFieldDocumentPassword = big.NewInt(1 << 0)
	resetFormsRequestFieldDocID            = big.NewInt(1 << 1)
	resetFormsRequestFieldLayerName        = big.NewInt(1 << 2)
	resetFormsRequestFieldFieldKey         = big.NewInt(1 << 3)
)

type ResetFormsRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string `json:"-" url:"-"`
	DocID            string  `json:"-" url:"-"`
	LayerName        string  `json:"-" url:"-"`
	FieldKey         string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ResetFormsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResetFormsRequest) SetDocumentPassword(documentPassword *string) {
	r.DocumentPassword = documentPassword
	r.require(resetFormsRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResetFormsRequest) SetDocID(docID string) {
	r.DocID = docID
	r.require(resetFormsRequestFieldDocID)
}

// SetLayerName sets the LayerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResetFormsRequest) SetLayerName(layerName string) {
	r.LayerName = layerName
	r.require(resetFormsRequestFieldLayerName)
}

// SetFieldKey sets the FieldKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResetFormsRequest) SetFieldKey(fieldKey string) {
	r.FieldKey = fieldKey
	r.require(resetFormsRequestFieldFieldKey)
}

var (
	setValueFormsRequestFieldDocumentPassword = big.NewInt(1 << 0)
	setValueFormsRequestFieldDocID            = big.NewInt(1 << 1)
	setValueFormsRequestFieldLayerName        = big.NewInt(1 << 2)
	setValueFormsRequestFieldFieldKey         = big.NewInt(1 << 3)
)

type SetValueFormsRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string                    `json:"-" url:"-"`
	DocID            string                     `json:"-" url:"-"`
	LayerName        string                     `json:"-" url:"-"`
	FieldKey         string                     `json:"-" url:"-"`
	Body             v3.DocFormsSetValueRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SetValueFormsRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SetValueFormsRequest) SetDocumentPassword(documentPassword *string) {
	s.DocumentPassword = documentPassword
	s.require(setValueFormsRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SetValueFormsRequest) SetDocID(docID string) {
	s.DocID = docID
	s.require(setValueFormsRequestFieldDocID)
}

// SetLayerName sets the LayerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SetValueFormsRequest) SetLayerName(layerName string) {
	s.LayerName = layerName
	s.require(setValueFormsRequestFieldLayerName)
}

// SetFieldKey sets the FieldKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SetValueFormsRequest) SetFieldKey(fieldKey string) {
	s.FieldKey = fieldKey
	s.require(setValueFormsRequestFieldFieldKey)
}

func (s *SetValueFormsRequest) UnmarshalJSON(data []byte) error {
	var body v3.DocFormsSetValueRequest
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	s.Body = body
	return nil
}

func (s *SetValueFormsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.Body)
}

type ExportDataFormsRequestFormat string

const (
	ExportDataFormsRequestFormatFdf  ExportDataFormsRequestFormat = "fdf"
	ExportDataFormsRequestFormatXfdf ExportDataFormsRequestFormat = "xfdf"
)

func NewExportDataFormsRequestFormatFromString(s string) (ExportDataFormsRequestFormat, error) {
	switch s {
	case "fdf":
		return ExportDataFormsRequestFormatFdf, nil
	case "xfdf":
		return ExportDataFormsRequestFormatXfdf, nil
	}
	var t ExportDataFormsRequestFormat
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (e ExportDataFormsRequestFormat) Ptr() *ExportDataFormsRequestFormat {
	return &e
}
