// Code generated by Fern. DO NOT EDIT.

package doc

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersExportDataFormsRequest(t *testing.T) {
	t.Run("SetDocumentPassword", func(t *testing.T) {
		obj := &ExportDataFormsRequest{}
		var fernTestValueDocumentPassword *string
		obj.SetDocumentPassword(fernTestValueDocumentPassword)
		assert.Equal(t, fernTestValueDocumentPassword, obj.DocumentPassword)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDocID", func(t *testing.T) {
		obj := &ExportDataFormsRequest{}
		var fernTestValueDocID string
		obj.SetDocID(fernTestValueDocID)
		assert.Equal(t, fernTestValueDocID, obj.DocID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLayerName", func(t *testing.T) {
		obj := &ExportDataFormsRequest{}
		var fernTestValueLayerName string
		obj.SetLayerName(fernTestValueLayerName)
		assert.Equal(t, fernTestValueLayerName, obj.LayerName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFormat", func(t *testing.T) {
		obj := &ExportDataFormsRequest{}
		var fernTestValueFormat *ExportDataFormsRequestFormat
		obj.SetFormat(fernTestValueFormat)
		assert.Equal(t, fernTestValueFormat, obj.Format)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitExportDataFormsRequest(t *testing.T) {
	t.Run("SetDocumentPassword_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ExportDataFormsRequest{}
		var fernTestValueDocumentPassword *string

		// Act
		obj.SetDocumentPassword(fernTestValueDocumentPassword)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDocID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ExportDataFormsRequest{}
		var fernTestValueDocID string

		// Act
		obj.SetDocID(fernTestValueDocID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLayerName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ExportDataFormsRequest{}
		var fernTestValueLayerName string

		// Act
		obj.SetLayerName(fernTestValueLayerName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFormat_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ExportDataFormsRequest{}
		var fernTestValueFormat *ExportDataFormsRequestFormat

		// Act
		obj.SetFormat(fernTestValueFormat)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetFormsRequest(t *testing.T) {
	t.Run("SetDocumentPassword", func(t *testing.T) {
		obj := &GetFormsRequest{}
		var fernTestValueDocumentPassword *string
		obj.SetDocumentPassword(fernTestValueDocumentPassword)
		assert.Equal(t, fernTestValueDocumentPassword, obj.DocumentPassword)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDocID", func(t *testing.T) {
		obj := &GetFormsRequest{}
		var fernTestValueDocID string
		obj.SetDocID(fernTestValueDocID)
		assert.Equal(t, fernTestValueDocID, obj.DocID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLayerName", func(t *testing.T) {
		obj := &GetFormsRequest{}
		var fernTestValueLayerName string
		obj.SetLayerName(fernTestValueLayerName)
		assert.Equal(t, fernTestValueLayerName, obj.LayerName)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetFormsRequest(t *testing.T) {
	t.Run("SetDocumentPassword_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetFormsRequest{}
		var fernTestValueDocumentPassword *string

		// Act
		obj.SetDocumentPassword(fernTestValueDocumentPassword)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDocID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetFormsRequest{}
		var fernTestValueDocID string

		// Act
		obj.SetDocID(fernTestValueDocID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLayerName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetFormsRequest{}
		var fernTestValueLayerName string

		// Act
		obj.SetLayerName(fernTestValueLayerName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersImportDataFormsRequest(t *testing.T) {
	t.Run("SetDocumentPassword", func(t *testing.T) {
		obj := &ImportDataFormsRequest{}
		var fernTestValueDocumentPassword *string
		obj.SetDocumentPassword(fernTestValueDocumentPassword)
		assert.Equal(t, fernTestValueDocumentPassword, obj.DocumentPassword)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDocID", func(t *testing.T) {
		obj := &ImportDataFormsRequest{}
		var fernTestValueDocID string
		obj.SetDocID(fernTestValueDocID)
		assert.Equal(t, fernTestValueDocID, obj.DocID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLayerName", func(t *testing.T) {
		obj := &ImportDataFormsRequest{}
		var fernTestValueLayerName string
		obj.SetLayerName(fernTestValueLayerName)
		assert.Equal(t, fernTestValueLayerName, obj.LayerName)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitImportDataFormsRequest(t *testing.T) {
	t.Run("SetDocumentPassword_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ImportDataFormsRequest{}
		var fernTestValueDocumentPassword *string

		// Act
		obj.SetDocumentPassword(fernTestValueDocumentPassword)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDocID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ImportDataFormsRequest{}
		var fernTestValueDocID string

		// Act
		obj.SetDocID(fernTestValueDocID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLayerName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ImportDataFormsRequest{}
		var fernTestValueLayerName string

		// Act
		obj.SetLayerName(fernTestValueLayerName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersResetFormsRequest(t *testing.T) {
	t.Run("SetDocumentPassword", func(t *testing.T) {
		obj := &ResetFormsRequest{}
		var fernTestValueDocumentPassword *string
		obj.SetDocumentPassword(fernTestValueDocumentPassword)
		assert.Equal(t, fernTestValueDocumentPassword, obj.DocumentPassword)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDocID", func(t *testing.T) {
		obj := &ResetFormsRequest{}
		var fernTestValueDocID string
		obj.SetDocID(fernTestValueDocID)
		assert.Equal(t, fernTestValueDocID, obj.DocID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLayerName", func(t *testing.T) {
		obj := &ResetFormsRequest{}
		var fernTestValueLayerName string
		obj.SetLayerName(fernTestValueLayerName)
		assert.Equal(t, fernTestValueLayerName, obj.LayerName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFieldKey", func(t *testing.T) {
		obj := &ResetFormsRequest{}
		var fernTestValueFieldKey string
		obj.SetFieldKey(fernTestValueFieldKey)
		assert.Equal(t, fernTestValueFieldKey, obj.FieldKey)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitResetFormsRequest(t *testing.T) {
	t.Run("SetDocumentPassword_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ResetFormsRequest{}
		var fernTestValueDocumentPassword *string

		// Act
		obj.SetDocumentPassword(fernTestValueDocumentPassword)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDocID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ResetFormsRequest{}
		var fernTestValueDocID string

		// Act
		obj.SetDocID(fernTestValueDocID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLayerName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ResetFormsRequest{}
		var fernTestValueLayerName string

		// Act
		obj.SetLayerName(fernTestValueLayerName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFieldKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ResetFormsRequest{}
		var fernTestValueFieldKey string

		// Act
		obj.SetFieldKey(fernTestValueFieldKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSetValueFormsRequest(t *testing.T) {
	t.Run("SetDocumentPassword", func(t *testing.T) {
		obj := &SetValueFormsRequest{}
		var fernTestValueDocumentPassword *string
		obj.SetDocumentPassword(fernTestValueDocumentPassword)
		assert.Equal(t, fernTestValueDocumentPassword, obj.DocumentPassword)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDocID", func(t *testing.T) {
		obj := &SetValueFormsRequest{}
		var fernTestValueDocID string
		obj.SetDocID(fernTestValueDocID)
		assert.Equal(t, fernTestValueDocID, obj.DocID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLayerName", func(t *testing.T) {
		obj := &SetValueFormsRequest{}
		var fernTestValueLayerName string
		obj.SetLayerName(fernTestValueLayerName)
		assert.Equal(t, fernTestValueLayerName, obj.LayerName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFieldKey", func(t *testing.T) {
		obj := &SetValueFormsRequest{}
		var fernTestValueFieldKey string
		obj.SetFieldKey(fernTestValueFieldKey)
		assert.Equal(t, fernTestValueFieldKey, obj.FieldKey)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitSetValueFormsRequest(t *testing.T) {
	t.Run("SetDocumentPassword_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetValueFormsRequest{}
		var fernTestValueDocumentPassword *string

		// Act
		obj.SetDocumentPassword(fernTestValueDocumentPassword)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDocID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetValueFormsRequest{}
		var fernTestValueDocID string

		// Act
		obj.SetDocID(fernTestValueDocID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLayerName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetValueFormsRequest{}
		var fernTestValueLayerName string

		// Act
		obj.SetLayerName(fernTestValueLayerName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFieldKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetValueFormsRequest{}
		var fernTestValueFieldKey string

		// Act
		obj.SetFieldKey(fernTestValueFieldKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestEnumExportDataFormsRequestFormat(t *testing.T) {
	t.Run("NewFromString_fdf", func(t *testing.T) {
		t.Parallel()
		val, err := NewExportDataFormsRequestFormatFromString("fdf")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ExportDataFormsRequestFormat("fdf"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_xfdf", func(t *testing.T) {
		t.Parallel()
		val, err := NewExportDataFormsRequestFormatFromString("xfdf")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ExportDataFormsRequestFormat("xfdf"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewExportDataFormsRequestFormatFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewExportDataFormsRequestFormatFromString("fdf")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}
