// Code generated by Fern. DO NOT EDIT.

package doc

import (
	json "encoding/json"
	v3 "github.com/embedpdf/cloudpdf-sdk-go/v3"
	big "math/big"
)

var (
	applyRedactionsRequestFieldDocumentPassword = big.NewInt(1 << 0)
	applyRedactionsRequestFieldDocID            = big.NewInt(1 << 1)
	applyRedactionsRequestFieldLayerName        = big.NewInt(1 << 2)
)

type ApplyRedactionsRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string                      `json:"-" url:"-"`
	DocID            string                       `json:"-" url:"-"`
	LayerName        string                       `json:"-" url:"-"`
	Body             v3.DocRedactionsApplyRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *ApplyRedactionsRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *ApplyRedactionsRequest) SetDocumentPassword(documentPassword *string) {
	a.DocumentPassword = documentPassword
	a.require(applyRedactionsRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *ApplyRedactionsRequest) SetDocID(docID string) {
	a.DocID = docID
	a.require(applyRedactionsRequestFieldDocID)
}

// SetLayerName sets the LayerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *ApplyRedactionsRequest) SetLayerName(layerName string) {
	a.LayerName = layerName
	a.require(applyRedactionsRequestFieldLayerName)
}

func (a *ApplyRedactionsRequest) UnmarshalJSON(data []byte) error {
	var body v3.DocRedactionsApplyRequest
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	a.Body = body
	return nil
}

func (a *ApplyRedactionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(a.Body)
}
