// Code generated by Fern. DO NOT EDIT.

package doc

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/embedpdf/cloudpdf-sdk-go/v3/internal"
	io "io"
	big "math/big"
)

var (
	abortSignaturesRequestFieldDocumentPassword = big.NewInt(1 << 0)
	abortSignaturesRequestFieldDocID            = big.NewInt(1 << 1)
	abortSignaturesRequestFieldLayerName        = big.NewInt(1 << 2)
	abortSignaturesRequestFieldSigningID        = big.NewInt(1 << 3)
)

type AbortSignaturesRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string `json:"-" url:"-"`
	DocID            string  `json:"-" url:"-"`
	LayerName        string  `json:"-" url:"-"`
	SigningID        string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AbortSignaturesRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AbortSignaturesRequest) SetDocumentPassword(documentPassword *string) {
	a.DocumentPassword = documentPassword
	a.require(abortSignaturesRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AbortSignaturesRequest) SetDocID(docID string) {
	a.DocID = docID
	a.require(abortSignaturesRequestFieldDocID)
}

// SetLayerName sets the LayerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AbortSignaturesRequest) SetLayerName(layerName string) {
	a.LayerName = layerName
	a.require(abortSignaturesRequestFieldLayerName)
}

// SetSigningID sets the SigningID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AbortSignaturesRequest) SetSigningID(signingID string) {
	a.SigningID = signingID
	a.require(abortSignaturesRequestFieldSigningID)
}

var (
	analysisSignaturesRequestFieldDocumentPassword = big.NewInt(1 << 0)
	analysisSignaturesRequestFieldDocID            = big.NewInt(1 << 1)
	analysisSignaturesRequestFieldLayerName        = big.NewInt(1 << 2)
	analysisSignaturesRequestFieldSinceSignature   = big.NewInt(1 << 3)
	analysisSignaturesRequestFieldSinceRevision    = big.NewInt(1 << 4)
	analysisSignaturesRequestFieldLevel            = big.NewInt(1 << 5)
)

type AnalysisSignaturesRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string                         `json:"-" url:"-"`
	DocID            string                          `json:"-" url:"-"`
	LayerName        string                          `json:"-" url:"-"`
	SinceSignature   *int                            `json:"-" url:"since.signature,omitempty"`
	SinceRevision    *int                            `json:"-" url:"since.revision,omitempty"`
	Level            *AnalysisSignaturesRequestLevel `json:"-" url:"level,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AnalysisSignaturesRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AnalysisSignaturesRequest) SetDocumentPassword(documentPassword *string) {
	a.DocumentPassword = documentPassword
	a.require(analysisSignaturesRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AnalysisSignaturesRequest) SetDocID(docID string) {
	a.DocID = docID
	a.require(analysisSignaturesRequestFieldDocID)
}

// SetLayerName sets the LayerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AnalysisSignaturesRequest) SetLayerName(layerName string) {
	a.LayerName = layerName
	a.require(analysisSignaturesRequestFieldLayerName)
}

// SetSinceSignature sets the SinceSignature field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AnalysisSignaturesRequest) SetSinceSignature(sinceSignature *int) {
	a.SinceSignature = sinceSignature
	a.require(analysisSignaturesRequestFieldSinceSignature)
}

// SetSinceRevision sets the SinceRevision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AnalysisSignaturesRequest) SetSinceRevision(sinceRevision *int) {
	a.SinceRevision = sinceRevision
	a.require(analysisSignaturesRequestFieldSinceRevision)
}

// SetLevel sets the Level field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AnalysisSignaturesRequest) SetLevel(level *AnalysisSignaturesRequestLevel) {
	a.Level = level
	a.require(analysisSignaturesRequestFieldLevel)
}

var (
	docSignaturesCompleteRequestFieldDocumentPassword = big.NewInt(1 << 0)
	docSignaturesCompleteRequestFieldDocID            = big.NewInt(1 << 1)
	docSignaturesCompleteRequestFieldLayerName        = big.NewInt(1 << 2)
	docSignaturesCompleteRequestFieldSigningID        = big.NewInt(1 << 3)
	docSignaturesCompleteRequestFieldCms              = big.NewInt(1 << 4)
	docSignaturesCompleteRequestFieldExpectedVersion  = big.NewInt(1 << 5)
)

type DocSignaturesCompleteRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string                                      `json:"-" url:"-"`
	DocID            string                                       `json:"-" url:"-"`
	LayerName        string                                       `json:"-" url:"-"`
	SigningID        string                                       `json:"-" url:"-"`
	Cms              string                                       `json:"cms" url:"-"`
	ExpectedVersion  *DocSignaturesCompleteRequestExpectedVersion `json:"expectedVersion" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DocSignaturesCompleteRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocSignaturesCompleteRequest) SetDocumentPassword(documentPassword *string) {
	d.DocumentPassword = documentPassword
	d.require(docSignaturesCompleteRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocSignaturesCompleteRequest) SetDocID(docID string) {
	d.DocID = docID
	d.require(docSignaturesCompleteRequestFieldDocID)
}

// SetLayerName sets the LayerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocSignaturesCompleteRequest) SetLayerName(layerName string) {
	d.LayerName = layerName
	d.require(docSignaturesCompleteRequestFieldLayerName)
}

// SetSigningID sets the SigningID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocSignaturesCompleteRequest) SetSigningID(signingID string) {
	d.SigningID = signingID
	d.require(docSignaturesCompleteRequestFieldSigningID)
}

// SetCms sets the Cms field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocSignaturesCompleteRequest) SetCms(cms string) {
	d.Cms = cms
	d.require(docSignaturesCompleteRequestFieldCms)
}

// SetExpectedVersion sets the ExpectedVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocSignaturesCompleteRequest) SetExpectedVersion(expectedVersion *DocSignaturesCompleteRequestExpectedVersion) {
	d.ExpectedVersion = expectedVersion
	d.require(docSignaturesCompleteRequestFieldExpectedVersion)
}

func (d *DocSignaturesCompleteRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler DocSignaturesCompleteRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*d = DocSignaturesCompleteRequest(body)
	return nil
}

func (d *DocSignaturesCompleteRequest) MarshalJSON() ([]byte, error) {
	type embed DocSignaturesCompleteRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	listSignaturesRequestFieldDocumentPassword = big.NewInt(1 << 0)
	listSignaturesRequestFieldDocID            = big.NewInt(1 << 1)
	listSignaturesRequestFieldLayerName        = big.NewInt(1 << 2)
)

type ListSignaturesRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string `json:"-" url:"-"`
	DocID            string  `json:"-" url:"-"`
	LayerName        string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListSignaturesRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSignaturesRequest) SetDocumentPassword(documentPassword *string) {
	l.DocumentPassword = documentPassword
	l.require(listSignaturesRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSignaturesRequest) SetDocID(docID string) {
	l.DocID = docID
	l.require(listSignaturesRequestFieldDocID)
}

// SetLayerName sets the LayerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSignaturesRequest) SetLayerName(layerName string) {
	l.LayerName = layerName
	l.require(listSignaturesRequestFieldLayerName)
}

var (
	prepareSignaturesRequestFieldDocumentPassword = big.NewInt(1 << 0)
	prepareSignaturesRequestFieldDocID            = big.NewInt(1 << 1)
	prepareSignaturesRequestFieldLayerName        = big.NewInt(1 << 2)
)

type PrepareSignaturesRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string   `json:"-" url:"-"`
	DocID            string    `json:"-" url:"-"`
	LayerName        string    `json:"-" url:"-"`
	File             io.Reader `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PrepareSignaturesRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PrepareSignaturesRequest) SetDocumentPassword(documentPassword *string) {
	p.DocumentPassword = documentPassword
	p.require(prepareSignaturesRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PrepareSignaturesRequest) SetDocID(docID string) {
	p.DocID = docID
	p.require(prepareSignaturesRequestFieldDocID)
}

// SetLayerName sets the LayerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PrepareSignaturesRequest) SetLayerName(layerName string) {
	p.LayerName = layerName
	p.require(prepareSignaturesRequestFieldLayerName)
}

func (p *PrepareSignaturesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler PrepareSignaturesRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = PrepareSignaturesRequest(body)
	return nil
}

func (p *PrepareSignaturesRequest) MarshalJSON() ([]byte, error) {
	type embed PrepareSignaturesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

type AnalysisSignaturesRequestLevel string

const (
	AnalysisSignaturesRequestLevelNone     AnalysisSignaturesRequestLevel = "none"
	AnalysisSignaturesRequestLevelLta      AnalysisSignaturesRequestLevel = "lta"
	AnalysisSignaturesRequestLevelFill     AnalysisSignaturesRequestLevel = "fill"
	AnalysisSignaturesRequestLevelAnnotate AnalysisSignaturesRequestLevel = "annotate"
)

func NewAnalysisSignaturesRequestLevelFromString(s string) (AnalysisSignaturesRequestLevel, error) {
	switch s {
	case "none":
		return AnalysisSignaturesRequestLevelNone, nil
	case "lta":
		return AnalysisSignaturesRequestLevelLta, nil
	case "fill":
		return AnalysisSignaturesRequestLevelFill, nil
	case "annotate":
		return AnalysisSignaturesRequestLevelAnnotate, nil
	}
	var t AnalysisSignaturesRequestLevel
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AnalysisSignaturesRequestLevel) Ptr() *AnalysisSignaturesRequestLevel {
	return &a
}

var (
	docSignaturesCompleteRequestExpectedVersionFieldBaseSha256   = big.NewInt(1 << 0)
	docSignaturesCompleteRequestExpectedVersionFieldEditsVersion = big.NewInt(1 << 1)
)

type DocSignaturesCompleteRequestExpectedVersion struct {
	BaseSha256   string `json:"baseSha256" url:"baseSha256"`
	EditsVersion int    `json:"editsVersion" url:"editsVersion"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DocSignaturesCompleteRequestExpectedVersion) GetBaseSha256() string {
	if d == nil {
		return ""
	}
	return d.BaseSha256
}

func (d *DocSignaturesCompleteRequestExpectedVersion) GetEditsVersion() int {
	if d == nil {
		return 0
	}
	return d.EditsVersion
}

func (d *DocSignaturesCompleteRequestExpectedVersion) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DocSignaturesCompleteRequestExpectedVersion) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetBaseSha256 sets the BaseSha256 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocSignaturesCompleteRequestExpectedVersion) SetBaseSha256(baseSha256 string) {
	d.BaseSha256 = baseSha256
	d.require(docSignaturesCompleteRequestExpectedVersionFieldBaseSha256)
}

// SetEditsVersion sets the EditsVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DocSignaturesCompleteRequestExpectedVersion) SetEditsVersion(editsVersion int) {
	d.EditsVersion = editsVersion
	d.require(docSignaturesCompleteRequestExpectedVersionFieldEditsVersion)
}

func (d *DocSignaturesCompleteRequestExpectedVersion) UnmarshalJSON(data []byte) error {
	type unmarshaler DocSignaturesCompleteRequestExpectedVersion
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DocSignaturesCompleteRequestExpectedVersion(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DocSignaturesCompleteRequestExpectedVersion) MarshalJSON() ([]byte, error) {
	type embed DocSignaturesCompleteRequestExpectedVersion
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DocSignaturesCompleteRequestExpectedVersion) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}
