// Code generated by Fern. DO NOT EDIT.

package doc

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersAnalysisVersionsRequest(t *testing.T) {
	t.Run("SetDocumentPassword", func(t *testing.T) {
		obj := &AnalysisVersionsRequest{}
		var fernTestValueDocumentPassword *string
		obj.SetDocumentPassword(fernTestValueDocumentPassword)
		assert.Equal(t, fernTestValueDocumentPassword, obj.DocumentPassword)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDocID", func(t *testing.T) {
		obj := &AnalysisVersionsRequest{}
		var fernTestValueDocID string
		obj.SetDocID(fernTestValueDocID)
		assert.Equal(t, fernTestValueDocID, obj.DocID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSha", func(t *testing.T) {
		obj := &AnalysisVersionsRequest{}
		var fernTestValueSha string
		obj.SetSha(fernTestValueSha)
		assert.Equal(t, fernTestValueSha, obj.Sha)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSinceSignature", func(t *testing.T) {
		obj := &AnalysisVersionsRequest{}
		var fernTestValueSinceSignature *int
		obj.SetSinceSignature(fernTestValueSinceSignature)
		assert.Equal(t, fernTestValueSinceSignature, obj.SinceSignature)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSinceRevision", func(t *testing.T) {
		obj := &AnalysisVersionsRequest{}
		var fernTestValueSinceRevision *int
		obj.SetSinceRevision(fernTestValueSinceRevision)
		assert.Equal(t, fernTestValueSinceRevision, obj.SinceRevision)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLevel", func(t *testing.T) {
		obj := &AnalysisVersionsRequest{}
		var fernTestValueLevel *AnalysisVersionsRequestLevel
		obj.SetLevel(fernTestValueLevel)
		assert.Equal(t, fernTestValueLevel, obj.Level)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUntil", func(t *testing.T) {
		obj := &AnalysisVersionsRequest{}
		var fernTestValueUntil *int
		obj.SetUntil(fernTestValueUntil)
		assert.Equal(t, fernTestValueUntil, obj.Until)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPolicy", func(t *testing.T) {
		obj := &AnalysisVersionsRequest{}
		var fernTestValuePolicy *int
		obj.SetPolicy(fernTestValuePolicy)
		assert.Equal(t, fernTestValuePolicy, obj.Policy)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitAnalysisVersionsRequest(t *testing.T) {
	t.Run("SetDocumentPassword_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalysisVersionsRequest{}
		var fernTestValueDocumentPassword *string

		// Act
		obj.SetDocumentPassword(fernTestValueDocumentPassword)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDocID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalysisVersionsRequest{}
		var fernTestValueDocID string

		// Act
		obj.SetDocID(fernTestValueDocID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSha_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalysisVersionsRequest{}
		var fernTestValueSha string

		// Act
		obj.SetSha(fernTestValueSha)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSinceSignature_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalysisVersionsRequest{}
		var fernTestValueSinceSignature *int

		// Act
		obj.SetSinceSignature(fernTestValueSinceSignature)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSinceRevision_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalysisVersionsRequest{}
		var fernTestValueSinceRevision *int

		// Act
		obj.SetSinceRevision(fernTestValueSinceRevision)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLevel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalysisVersionsRequest{}
		var fernTestValueLevel *AnalysisVersionsRequestLevel

		// Act
		obj.SetLevel(fernTestValueLevel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUntil_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalysisVersionsRequest{}
		var fernTestValueUntil *int

		// Act
		obj.SetUntil(fernTestValueUntil)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPolicy_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AnalysisVersionsRequest{}
		var fernTestValuePolicy *int

		// Act
		obj.SetPolicy(fernTestValuePolicy)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDownloadVersionsRequest(t *testing.T) {
	t.Run("SetDocumentPassword", func(t *testing.T) {
		obj := &DownloadVersionsRequest{}
		var fernTestValueDocumentPassword *string
		obj.SetDocumentPassword(fernTestValueDocumentPassword)
		assert.Equal(t, fernTestValueDocumentPassword, obj.DocumentPassword)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDocID", func(t *testing.T) {
		obj := &DownloadVersionsRequest{}
		var fernTestValueDocID string
		obj.SetDocID(fernTestValueDocID)
		assert.Equal(t, fernTestValueDocID, obj.DocID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSha", func(t *testing.T) {
		obj := &DownloadVersionsRequest{}
		var fernTestValueSha string
		obj.SetSha(fernTestValueSha)
		assert.Equal(t, fernTestValueSha, obj.Sha)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitDownloadVersionsRequest(t *testing.T) {
	t.Run("SetDocumentPassword_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DownloadVersionsRequest{}
		var fernTestValueDocumentPassword *string

		// Act
		obj.SetDocumentPassword(fernTestValueDocumentPassword)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDocID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DownloadVersionsRequest{}
		var fernTestValueDocID string

		// Act
		obj.SetDocID(fernTestValueDocID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSha_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DownloadVersionsRequest{}
		var fernTestValueSha string

		// Act
		obj.SetSha(fernTestValueSha)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListVersionsRequest(t *testing.T) {
	t.Run("SetDocumentPassword", func(t *testing.T) {
		obj := &ListVersionsRequest{}
		var fernTestValueDocumentPassword *string
		obj.SetDocumentPassword(fernTestValueDocumentPassword)
		assert.Equal(t, fernTestValueDocumentPassword, obj.DocumentPassword)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDocID", func(t *testing.T) {
		obj := &ListVersionsRequest{}
		var fernTestValueDocID string
		obj.SetDocID(fernTestValueDocID)
		assert.Equal(t, fernTestValueDocID, obj.DocID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitListVersionsRequest(t *testing.T) {
	t.Run("SetDocumentPassword_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListVersionsRequest{}
		var fernTestValueDocumentPassword *string

		// Act
		obj.SetDocumentPassword(fernTestValueDocumentPassword)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDocID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListVersionsRequest{}
		var fernTestValueDocID string

		// Act
		obj.SetDocID(fernTestValueDocID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersRevisionVersionsRequest(t *testing.T) {
	t.Run("SetDocumentPassword", func(t *testing.T) {
		obj := &RevisionVersionsRequest{}
		var fernTestValueDocumentPassword *string
		obj.SetDocumentPassword(fernTestValueDocumentPassword)
		assert.Equal(t, fernTestValueDocumentPassword, obj.DocumentPassword)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDocID", func(t *testing.T) {
		obj := &RevisionVersionsRequest{}
		var fernTestValueDocID string
		obj.SetDocID(fernTestValueDocID)
		assert.Equal(t, fernTestValueDocID, obj.DocID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSha", func(t *testing.T) {
		obj := &RevisionVersionsRequest{}
		var fernTestValueSha string
		obj.SetSha(fernTestValueSha)
		assert.Equal(t, fernTestValueSha, obj.Sha)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIndex", func(t *testing.T) {
		obj := &RevisionVersionsRequest{}
		var fernTestValueIndex int
		obj.SetIndex(fernTestValueIndex)
		assert.Equal(t, fernTestValueIndex, obj.Index)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitRevisionVersionsRequest(t *testing.T) {
	t.Run("SetDocumentPassword_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RevisionVersionsRequest{}
		var fernTestValueDocumentPassword *string

		// Act
		obj.SetDocumentPassword(fernTestValueDocumentPassword)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDocID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RevisionVersionsRequest{}
		var fernTestValueDocID string

		// Act
		obj.SetDocID(fernTestValueDocID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSha_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RevisionVersionsRequest{}
		var fernTestValueSha string

		// Act
		obj.SetSha(fernTestValueSha)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIndex_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RevisionVersionsRequest{}
		var fernTestValueIndex int

		// Act
		obj.SetIndex(fernTestValueIndex)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSignatureContentsVersionsRequest(t *testing.T) {
	t.Run("SetDocumentPassword", func(t *testing.T) {
		obj := &SignatureContentsVersionsRequest{}
		var fernTestValueDocumentPassword *string
		obj.SetDocumentPassword(fernTestValueDocumentPassword)
		assert.Equal(t, fernTestValueDocumentPassword, obj.DocumentPassword)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDocID", func(t *testing.T) {
		obj := &SignatureContentsVersionsRequest{}
		var fernTestValueDocID string
		obj.SetDocID(fernTestValueDocID)
		assert.Equal(t, fernTestValueDocID, obj.DocID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSha", func(t *testing.T) {
		obj := &SignatureContentsVersionsRequest{}
		var fernTestValueSha string
		obj.SetSha(fernTestValueSha)
		assert.Equal(t, fernTestValueSha, obj.Sha)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFieldKey", func(t *testing.T) {
		obj := &SignatureContentsVersionsRequest{}
		var fernTestValueFieldKey string
		obj.SetFieldKey(fernTestValueFieldKey)
		assert.Equal(t, fernTestValueFieldKey, obj.FieldKey)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitSignatureContentsVersionsRequest(t *testing.T) {
	t.Run("SetDocumentPassword_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SignatureContentsVersionsRequest{}
		var fernTestValueDocumentPassword *string

		// Act
		obj.SetDocumentPassword(fernTestValueDocumentPassword)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDocID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SignatureContentsVersionsRequest{}
		var fernTestValueDocID string

		// Act
		obj.SetDocID(fernTestValueDocID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSha_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SignatureContentsVersionsRequest{}
		var fernTestValueSha string

		// Act
		obj.SetSha(fernTestValueSha)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFieldKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SignatureContentsVersionsRequest{}
		var fernTestValueFieldKey string

		// Act
		obj.SetFieldKey(fernTestValueFieldKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSignatureDigestVersionsRequest(t *testing.T) {
	t.Run("SetDocumentPassword", func(t *testing.T) {
		obj := &SignatureDigestVersionsRequest{}
		var fernTestValueDocumentPassword *string
		obj.SetDocumentPassword(fernTestValueDocumentPassword)
		assert.Equal(t, fernTestValueDocumentPassword, obj.DocumentPassword)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDocID", func(t *testing.T) {
		obj := &SignatureDigestVersionsRequest{}
		var fernTestValueDocID string
		obj.SetDocID(fernTestValueDocID)
		assert.Equal(t, fernTestValueDocID, obj.DocID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSha", func(t *testing.T) {
		obj := &SignatureDigestVersionsRequest{}
		var fernTestValueSha string
		obj.SetSha(fernTestValueSha)
		assert.Equal(t, fernTestValueSha, obj.Sha)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFieldKey", func(t *testing.T) {
		obj := &SignatureDigestVersionsRequest{}
		var fernTestValueFieldKey string
		obj.SetFieldKey(fernTestValueFieldKey)
		assert.Equal(t, fernTestValueFieldKey, obj.FieldKey)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAlgorithm", func(t *testing.T) {
		obj := &SignatureDigestVersionsRequest{}
		var fernTestValueAlgorithm SignatureDigestVersionsRequestAlgorithm
		obj.SetAlgorithm(fernTestValueAlgorithm)
		assert.Equal(t, fernTestValueAlgorithm, obj.Algorithm)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitSignatureDigestVersionsRequest(t *testing.T) {
	t.Run("SetDocumentPassword_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SignatureDigestVersionsRequest{}
		var fernTestValueDocumentPassword *string

		// Act
		obj.SetDocumentPassword(fernTestValueDocumentPassword)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDocID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SignatureDigestVersionsRequest{}
		var fernTestValueDocID string

		// Act
		obj.SetDocID(fernTestValueDocID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSha_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SignatureDigestVersionsRequest{}
		var fernTestValueSha string

		// Act
		obj.SetSha(fernTestValueSha)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFieldKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SignatureDigestVersionsRequest{}
		var fernTestValueFieldKey string

		// Act
		obj.SetFieldKey(fernTestValueFieldKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAlgorithm_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SignatureDigestVersionsRequest{}
		var fernTestValueAlgorithm SignatureDigestVersionsRequestAlgorithm

		// Act
		obj.SetAlgorithm(fernTestValueAlgorithm)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSignaturesVersionsRequest(t *testing.T) {
	t.Run("SetDocumentPassword", func(t *testing.T) {
		obj := &SignaturesVersionsRequest{}
		var fernTestValueDocumentPassword *string
		obj.SetDocumentPassword(fernTestValueDocumentPassword)
		assert.Equal(t, fernTestValueDocumentPassword, obj.DocumentPassword)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDocID", func(t *testing.T) {
		obj := &SignaturesVersionsRequest{}
		var fernTestValueDocID string
		obj.SetDocID(fernTestValueDocID)
		assert.Equal(t, fernTestValueDocID, obj.DocID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSha", func(t *testing.T) {
		obj := &SignaturesVersionsRequest{}
		var fernTestValueSha string
		obj.SetSha(fernTestValueSha)
		assert.Equal(t, fernTestValueSha, obj.Sha)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitSignaturesVersionsRequest(t *testing.T) {
	t.Run("SetDocumentPassword_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SignaturesVersionsRequest{}
		var fernTestValueDocumentPassword *string

		// Act
		obj.SetDocumentPassword(fernTestValueDocumentPassword)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDocID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SignaturesVersionsRequest{}
		var fernTestValueDocID string

		// Act
		obj.SetDocID(fernTestValueDocID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSha_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SignaturesVersionsRequest{}
		var fernTestValueSha string

		// Act
		obj.SetSha(fernTestValueSha)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestEnumAnalysisVersionsRequestLevel(t *testing.T) {
	t.Run("NewFromString_none", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalysisVersionsRequestLevelFromString("none")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalysisVersionsRequestLevel("none"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_lta", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalysisVersionsRequestLevelFromString("lta")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalysisVersionsRequestLevel("lta"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_fill", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalysisVersionsRequestLevelFromString("fill")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalysisVersionsRequestLevel("fill"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_annotate", func(t *testing.T) {
		t.Parallel()
		val, err := NewAnalysisVersionsRequestLevelFromString("annotate")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, AnalysisVersionsRequestLevel("annotate"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewAnalysisVersionsRequestLevelFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewAnalysisVersionsRequestLevelFromString("none")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumSignatureDigestVersionsRequestAlgorithm(t *testing.T) {
	t.Run("NewFromString_sha1", func(t *testing.T) {
		t.Parallel()
		val, err := NewSignatureDigestVersionsRequestAlgorithmFromString("sha1")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SignatureDigestVersionsRequestAlgorithm("sha1"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_sha256", func(t *testing.T) {
		t.Parallel()
		val, err := NewSignatureDigestVersionsRequestAlgorithmFromString("sha256")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SignatureDigestVersionsRequestAlgorithm("sha256"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_sha384", func(t *testing.T) {
		t.Parallel()
		val, err := NewSignatureDigestVersionsRequestAlgorithmFromString("sha384")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SignatureDigestVersionsRequestAlgorithm("sha384"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_sha512", func(t *testing.T) {
		t.Parallel()
		val, err := NewSignatureDigestVersionsRequestAlgorithmFromString("sha512")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SignatureDigestVersionsRequestAlgorithm("sha512"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewSignatureDigestVersionsRequestAlgorithmFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewSignatureDigestVersionsRequestAlgorithmFromString("sha1")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}
