// Code generated by Fern. DO NOT EDIT.

package doc

import (
	fmt "fmt"
	big "math/big"
)

var (
	analysisVersionsRequestFieldDocumentPassword = big.NewInt(1 << 0)
	analysisVersionsRequestFieldDocID            = big.NewInt(1 << 1)
	analysisVersionsRequestFieldSha              = big.NewInt(1 << 2)
	analysisVersionsRequestFieldSinceSignature   = big.NewInt(1 << 3)
	analysisVersionsRequestFieldSinceRevision    = big.NewInt(1 << 4)
	analysisVersionsRequestFieldLevel            = big.NewInt(1 << 5)
	analysisVersionsRequestFieldUntil            = big.NewInt(1 << 6)
	analysisVersionsRequestFieldPolicy           = big.NewInt(1 << 7)
)

type AnalysisVersionsRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string                       `json:"-" url:"-"`
	DocID            string                        `json:"-" url:"-"`
	Sha              string                        `json:"-" url:"-"`
	SinceSignature   *int                          `json:"-" url:"since.signature,omitempty"`
	SinceRevision    *int                          `json:"-" url:"since.revision,omitempty"`
	Level            *AnalysisVersionsRequestLevel `json:"-" url:"level,omitempty"`
	Until            *int                          `json:"-" url:"until,omitempty"`
	Policy           *int                          `json:"-" url:"policy,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AnalysisVersionsRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AnalysisVersionsRequest) SetDocumentPassword(documentPassword *string) {
	a.DocumentPassword = documentPassword
	a.require(analysisVersionsRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AnalysisVersionsRequest) SetDocID(docID string) {
	a.DocID = docID
	a.require(analysisVersionsRequestFieldDocID)
}

// SetSha sets the Sha field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AnalysisVersionsRequest) SetSha(sha string) {
	a.Sha = sha
	a.require(analysisVersionsRequestFieldSha)
}

// SetSinceSignature sets the SinceSignature field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AnalysisVersionsRequest) SetSinceSignature(sinceSignature *int) {
	a.SinceSignature = sinceSignature
	a.require(analysisVersionsRequestFieldSinceSignature)
}

// SetSinceRevision sets the SinceRevision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AnalysisVersionsRequest) SetSinceRevision(sinceRevision *int) {
	a.SinceRevision = sinceRevision
	a.require(analysisVersionsRequestFieldSinceRevision)
}

// SetLevel sets the Level field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AnalysisVersionsRequest) SetLevel(level *AnalysisVersionsRequestLevel) {
	a.Level = level
	a.require(analysisVersionsRequestFieldLevel)
}

// SetUntil sets the Until field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AnalysisVersionsRequest) SetUntil(until *int) {
	a.Until = until
	a.require(analysisVersionsRequestFieldUntil)
}

// SetPolicy sets the Policy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AnalysisVersionsRequest) SetPolicy(policy *int) {
	a.Policy = policy
	a.require(analysisVersionsRequestFieldPolicy)
}

var (
	downloadVersionsRequestFieldDocumentPassword = big.NewInt(1 << 0)
	downloadVersionsRequestFieldDocID            = big.NewInt(1 << 1)
	downloadVersionsRequestFieldSha              = big.NewInt(1 << 2)
)

type DownloadVersionsRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string `json:"-" url:"-"`
	DocID            string  `json:"-" url:"-"`
	Sha              string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DownloadVersionsRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadVersionsRequest) SetDocumentPassword(documentPassword *string) {
	d.DocumentPassword = documentPassword
	d.require(downloadVersionsRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadVersionsRequest) SetDocID(docID string) {
	d.DocID = docID
	d.require(downloadVersionsRequestFieldDocID)
}

// SetSha sets the Sha field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadVersionsRequest) SetSha(sha string) {
	d.Sha = sha
	d.require(downloadVersionsRequestFieldSha)
}

var (
	listVersionsRequestFieldDocumentPassword = big.NewInt(1 << 0)
	listVersionsRequestFieldDocID            = big.NewInt(1 << 1)
)

type ListVersionsRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string `json:"-" url:"-"`
	DocID            string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListVersionsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVersionsRequest) SetDocumentPassword(documentPassword *string) {
	l.DocumentPassword = documentPassword
	l.require(listVersionsRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVersionsRequest) SetDocID(docID string) {
	l.DocID = docID
	l.require(listVersionsRequestFieldDocID)
}

var (
	revisionVersionsRequestFieldDocumentPassword = big.NewInt(1 << 0)
	revisionVersionsRequestFieldDocID            = big.NewInt(1 << 1)
	revisionVersionsRequestFieldSha              = big.NewInt(1 << 2)
	revisionVersionsRequestFieldIndex            = big.NewInt(1 << 3)
)

type RevisionVersionsRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string `json:"-" url:"-"`
	DocID            string  `json:"-" url:"-"`
	Sha              string  `json:"-" url:"-"`
	Index            int     `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RevisionVersionsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevisionVersionsRequest) SetDocumentPassword(documentPassword *string) {
	r.DocumentPassword = documentPassword
	r.require(revisionVersionsRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevisionVersionsRequest) SetDocID(docID string) {
	r.DocID = docID
	r.require(revisionVersionsRequestFieldDocID)
}

// SetSha sets the Sha field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevisionVersionsRequest) SetSha(sha string) {
	r.Sha = sha
	r.require(revisionVersionsRequestFieldSha)
}

// SetIndex sets the Index field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevisionVersionsRequest) SetIndex(index int) {
	r.Index = index
	r.require(revisionVersionsRequestFieldIndex)
}

var (
	signatureContentsVersionsRequestFieldDocumentPassword = big.NewInt(1 << 0)
	signatureContentsVersionsRequestFieldDocID            = big.NewInt(1 << 1)
	signatureContentsVersionsRequestFieldSha              = big.NewInt(1 << 2)
	signatureContentsVersionsRequestFieldFieldKey         = big.NewInt(1 << 3)
)

type SignatureContentsVersionsRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string `json:"-" url:"-"`
	DocID            string  `json:"-" url:"-"`
	Sha              string  `json:"-" url:"-"`
	FieldKey         string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SignatureContentsVersionsRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SignatureContentsVersionsRequest) SetDocumentPassword(documentPassword *string) {
	s.DocumentPassword = documentPassword
	s.require(signatureContentsVersionsRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SignatureContentsVersionsRequest) SetDocID(docID string) {
	s.DocID = docID
	s.require(signatureContentsVersionsRequestFieldDocID)
}

// SetSha sets the Sha field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SignatureContentsVersionsRequest) SetSha(sha string) {
	s.Sha = sha
	s.require(signatureContentsVersionsRequestFieldSha)
}

// SetFieldKey sets the FieldKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SignatureContentsVersionsRequest) SetFieldKey(fieldKey string) {
	s.FieldKey = fieldKey
	s.require(signatureContentsVersionsRequestFieldFieldKey)
}

var (
	signatureDigestVersionsRequestFieldDocumentPassword = big.NewInt(1 << 0)
	signatureDigestVersionsRequestFieldDocID            = big.NewInt(1 << 1)
	signatureDigestVersionsRequestFieldSha              = big.NewInt(1 << 2)
	signatureDigestVersionsRequestFieldFieldKey         = big.NewInt(1 << 3)
	signatureDigestVersionsRequestFieldAlgorithm        = big.NewInt(1 << 4)
)

type SignatureDigestVersionsRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string                                 `json:"-" url:"-"`
	DocID            string                                  `json:"-" url:"-"`
	Sha              string                                  `json:"-" url:"-"`
	FieldKey         string                                  `json:"-" url:"-"`
	Algorithm        SignatureDigestVersionsRequestAlgorithm `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SignatureDigestVersionsRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SignatureDigestVersionsRequest) SetDocumentPassword(documentPassword *string) {
	s.DocumentPassword = documentPassword
	s.require(signatureDigestVersionsRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SignatureDigestVersionsRequest) SetDocID(docID string) {
	s.DocID = docID
	s.require(signatureDigestVersionsRequestFieldDocID)
}

// SetSha sets the Sha field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SignatureDigestVersionsRequest) SetSha(sha string) {
	s.Sha = sha
	s.require(signatureDigestVersionsRequestFieldSha)
}

// SetFieldKey sets the FieldKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SignatureDigestVersionsRequest) SetFieldKey(fieldKey string) {
	s.FieldKey = fieldKey
	s.require(signatureDigestVersionsRequestFieldFieldKey)
}

// SetAlgorithm sets the Algorithm field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SignatureDigestVersionsRequest) SetAlgorithm(algorithm SignatureDigestVersionsRequestAlgorithm) {
	s.Algorithm = algorithm
	s.require(signatureDigestVersionsRequestFieldAlgorithm)
}

var (
	signaturesVersionsRequestFieldDocumentPassword = big.NewInt(1 << 0)
	signaturesVersionsRequestFieldDocID            = big.NewInt(1 << 1)
	signaturesVersionsRequestFieldSha              = big.NewInt(1 << 2)
)

type SignaturesVersionsRequest struct {
	// Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.
	DocumentPassword *string `json:"-" url:"-"`
	DocID            string  `json:"-" url:"-"`
	Sha              string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SignaturesVersionsRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetDocumentPassword sets the DocumentPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SignaturesVersionsRequest) SetDocumentPassword(documentPassword *string) {
	s.DocumentPassword = documentPassword
	s.require(signaturesVersionsRequestFieldDocumentPassword)
}

// SetDocID sets the DocID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SignaturesVersionsRequest) SetDocID(docID string) {
	s.DocID = docID
	s.require(signaturesVersionsRequestFieldDocID)
}

// SetSha sets the Sha field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SignaturesVersionsRequest) SetSha(sha string) {
	s.Sha = sha
	s.require(signaturesVersionsRequestFieldSha)
}

type AnalysisVersionsRequestLevel string

const (
	AnalysisVersionsRequestLevelNone     AnalysisVersionsRequestLevel = "none"
	AnalysisVersionsRequestLevelLta      AnalysisVersionsRequestLevel = "lta"
	AnalysisVersionsRequestLevelFill     AnalysisVersionsRequestLevel = "fill"
	AnalysisVersionsRequestLevelAnnotate AnalysisVersionsRequestLevel = "annotate"
)

func NewAnalysisVersionsRequestLevelFromString(s string) (AnalysisVersionsRequestLevel, error) {
	switch s {
	case "none":
		return AnalysisVersionsRequestLevelNone, nil
	case "lta":
		return AnalysisVersionsRequestLevelLta, nil
	case "fill":
		return AnalysisVersionsRequestLevelFill, nil
	case "annotate":
		return AnalysisVersionsRequestLevelAnnotate, nil
	}
	var t AnalysisVersionsRequestLevel
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AnalysisVersionsRequestLevel) Ptr() *AnalysisVersionsRequestLevel {
	return &a
}

type SignatureDigestVersionsRequestAlgorithm string

const (
	SignatureDigestVersionsRequestAlgorithmSha1   SignatureDigestVersionsRequestAlgorithm = "sha1"
	SignatureDigestVersionsRequestAlgorithmSha256 SignatureDigestVersionsRequestAlgorithm = "sha256"
	SignatureDigestVersionsRequestAlgorithmSha384 SignatureDigestVersionsRequestAlgorithm = "sha384"
	SignatureDigestVersionsRequestAlgorithmSha512 SignatureDigestVersionsRequestAlgorithm = "sha512"
)

func NewSignatureDigestVersionsRequestAlgorithmFromString(s string) (SignatureDigestVersionsRequestAlgorithm, error) {
	switch s {
	case "sha1":
		return SignatureDigestVersionsRequestAlgorithmSha1, nil
	case "sha256":
		return SignatureDigestVersionsRequestAlgorithmSha256, nil
	case "sha384":
		return SignatureDigestVersionsRequestAlgorithmSha384, nil
	case "sha512":
		return SignatureDigestVersionsRequestAlgorithmSha512, nil
	}
	var t SignatureDigestVersionsRequestAlgorithm
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SignatureDigestVersionsRequestAlgorithm) Ptr() *SignatureDigestVersionsRequestAlgorithm {
	return &s
}
