// Code generated by Fern. DO NOT EDIT.

package signatures

import (
	context "context"

	cloudpdf "github.com/embedpdf/cloudpdf-sdk-go/v3"
	core "github.com/embedpdf/cloudpdf-sdk-go/v3/core"
	doc "github.com/embedpdf/cloudpdf-sdk-go/v3/doc"
	internal "github.com/embedpdf/cloudpdf-sdk-go/v3/internal"
	option "github.com/embedpdf/cloudpdf-sdk-go/v3/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Describes the bytes the layer is over: the base version's signatures plus the layer's own edits as the last revision. Signed bytes (contents, digests, revision prefixes) are served per base version under /versions.
//
// Example:
//
//	request := &doc.ListSignaturesRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	}
//	client.Doc.Signatures.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *doc.ListSignaturesRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocSignaturesList200Response, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &doc.AbortSignaturesRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    SigningID: "signingId",
//	}
//	client.Doc.Signatures.Abort(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Abort(
	ctx context.Context,
	request *doc.AbortSignaturesRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocSignaturesAbort200Response, error) {
	response, err := c.WithRawResponse.Abort(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// `cms` is the detached CMS over the prepared digest, base64. `expectedVersion` must be what prepare returned. Idempotent by signing id: the same CMS again answers `already-completed`. Every layer of the document then sits over the new version; refetch the manifest after a completion.
//
// Example:
//
//	request := &doc.DocSignaturesCompleteRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    SigningID: "signingId",
//	    Cms: "cms",
//	    ExpectedVersion: &doc.DocSignaturesCompleteRequestExpectedVersion{
//	        BaseSha256: "baseSha256",
//	        EditsVersion: 1,
//	    },
//	}
//	client.Doc.Signatures.Complete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Complete(
	ctx context.Context,
	request *doc.DocSignaturesCompleteRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocSignaturesComplete200Response, error) {
	response, err := c.WithRawResponse.Complete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Exactly one of `since.signature=<index>` or `since.revision=<index>`; the layer's pending edits are the end. `level=fill|annotate|lta|none` evaluates exploratorily and never becomes a verdict. For history between two base revisions use the version analysis.
//
// Example:
//
//	request := &doc.AnalysisSignaturesRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	}
//	client.Doc.Signatures.Analysis(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Analysis(
	ctx context.Context,
	request *doc.AnalysisSignaturesRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocSignaturesAnalysis200Response, error) {
	response, err := c.WithRawResponse.Analysis(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The multipart envelope: a JSON `body` part (field, subFilter, digest, contentsSize, signer, certify, lock, appearance) and an optional `resource:<key>` PDF part the body's `appearance.resource` names. A certification (`certify.permission`) additionally requires `doc.sign.certify`. The layer is read-only until the signing completes, is aborted, or expires (15 minutes). A layer behind the document head cannot sign (StaleBase).
//
// Example:
//
//	request := &doc.PrepareSignaturesRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    File: strings.NewReader(
//	        "",
//	    ),
//	}
//	client.Doc.Signatures.Prepare(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Prepare(
	ctx context.Context,
	request *doc.PrepareSignaturesRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocSignaturesPrepare200Response, error) {
	response, err := c.WithRawResponse.Prepare(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
