// Code generated by Fern. DO NOT EDIT.

package pages

import (
	context "context"

	cloudpdf "github.com/embedpdf/cloudpdf-sdk-go/v3"
	core "github.com/embedpdf/cloudpdf-sdk-go/v3/core"
	doc "github.com/embedpdf/cloudpdf-sdk-go/v3/doc"
	internal "github.com/embedpdf/cloudpdf-sdk-go/v3/internal"
	option "github.com/embedpdf/cloudpdf-sdk-go/v3/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	request := &doc.DeletePagesRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Body: map[string]any{
//	        "key": "value",
//	    },
//	}
//	client.Doc.Pages.Delete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Delete(
	ctx context.Context,
	request *doc.DeletePagesRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocPagesDelete200Response, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &doc.FlattenPagesRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Body: map[string]any{
//	        "key": "value",
//	    },
//	}
//	client.Doc.Pages.Flatten(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Flatten(
	ctx context.Context,
	request *doc.FlattenPagesRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocPagesFlatten200Response, error) {
	response, err := c.WithRawResponse.Flatten(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &doc.MovePagesRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Body: map[string]any{
//	        "key": "value",
//	    },
//	}
//	client.Doc.Pages.Move(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Move(
	ctx context.Context,
	request *doc.MovePagesRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocPagesMove200Response, error) {
	response, err := c.WithRawResponse.Move(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &doc.RotatePagesRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Body: map[string]any{
//	        "key": "value",
//	    },
//	}
//	client.Doc.Pages.Rotate(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Rotate(
	ctx context.Context,
	request *doc.RotatePagesRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocPagesRotate200Response, error) {
	response, err := c.WithRawResponse.Rotate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
