// Code generated by Fern. DO NOT EDIT.

package pages

import (
	context "context"
	io "io"

	cloudpdf "github.com/embedpdf/cloudpdf-sdk-go/v3"
	core "github.com/embedpdf/cloudpdf-sdk-go/v3/core"
	doc "github.com/embedpdf/cloudpdf-sdk-go/v3/doc"
	internal "github.com/embedpdf/cloudpdf-sdk-go/v3/internal"
	option "github.com/embedpdf/cloudpdf-sdk-go/v3/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	request := &doc.DocPagesSetScaleRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Pon: 1,
//	}
//	client.Doc.Pages.SetScale(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) SetScale(
	ctx context.Context,
	request *doc.DocPagesSetScaleRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocPagesSetScale200Response, error) {
	response, err := c.WithRawResponse.SetScale(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &doc.ViewportsPagesRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Pon: 1,
//	}
//	client.Doc.Pages.Viewports(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Viewports(
	ctx context.Context,
	request *doc.ViewportsPagesRequest,
	opts ...option.RequestOption,
) (cloudpdf.DocPagesViewports200Response, error) {
	response, err := c.WithRawResponse.Viewports(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &doc.DeletePagesRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Body: map[string]any{
//	        "key": "value",
//	    },
//	}
//	client.Doc.Pages.Delete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Delete(
	ctx context.Context,
	request *doc.DeletePagesRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocPagesDelete200Response, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// A read, not a mutation: the source document is untouched and no event is published. Body is `{"pageObjectNumbers": number[]}`; the response body is the new PDF.
//
// Example:
//
//	request := &doc.ExtractPagesRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Body: map[string]any{
//	        "string": map[string]any{
//	            "key": "value",
//	        },
//	    },
//	}
//	client.Doc.Pages.Extract(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Extract(
	ctx context.Context,
	request *doc.ExtractPagesRequest,
	opts ...option.RequestOption,
) (io.Reader, error) {
	response, err := c.WithRawResponse.Extract(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &doc.FlattenPagesRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Body: map[string]any{
//	        "key": "value",
//	    },
//	}
//	client.Doc.Pages.Flatten(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Flatten(
	ctx context.Context,
	request *doc.FlattenPagesRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocPagesFlatten200Response, error) {
	response, err := c.WithRawResponse.Flatten(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Multipart mutation envelope: a `body` field holding `{"destIndex"?: number}` (omitted → append) plus a `resource:source` file part carrying the standalone PDF whose pages are copied in. The inserted copies get fresh page object numbers, returned in insertion order.
//
// Example:
//
//	request := &doc.InsertPagesRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    File: strings.NewReader(
//	        "",
//	    ),
//	}
//	client.Doc.Pages.Insert(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Insert(
	ctx context.Context,
	request *doc.InsertPagesRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocPagesInsert200Response, error) {
	response, err := c.WithRawResponse.Insert(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Body is `{"size": {"width", "height"}, "count"?, "destIndex"?}` — size in PDF points, count in [1, 100], destIndex omitted → append.
//
// Example:
//
//	request := &doc.InsertBlankPagesRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Body: map[string]any{
//	        "key": "value",
//	    },
//	}
//	client.Doc.Pages.InsertBlank(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) InsertBlank(
	ctx context.Context,
	request *doc.InsertBlankPagesRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocPagesInsertBlank200Response, error) {
	response, err := c.WithRawResponse.InsertBlank(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &doc.MovePagesRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Body: map[string]any{
//	        "key": "value",
//	    },
//	}
//	client.Doc.Pages.Move(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Move(
	ctx context.Context,
	request *doc.MovePagesRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocPagesMove200Response, error) {
	response, err := c.WithRawResponse.Move(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &doc.SetNamePagesRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Body: map[string]any{
//	        "key": "value",
//	    },
//	}
//	client.Doc.Pages.SetName(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) SetName(
	ctx context.Context,
	request *doc.SetNamePagesRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocPagesSetName200Response, error) {
	response, err := c.WithRawResponse.SetName(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &doc.RemoveNamePagesRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Body: map[string]any{
//	        "key": "value",
//	    },
//	}
//	client.Doc.Pages.RemoveName(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) RemoveName(
	ctx context.Context,
	request *doc.RemoveNamePagesRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocPagesRemoveName200Response, error) {
	response, err := c.WithRawResponse.RemoveName(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &doc.RotatePagesRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Body: map[string]any{
//	        "key": "value",
//	    },
//	}
//	client.Doc.Pages.Rotate(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Rotate(
	ctx context.Context,
	request *doc.RotatePagesRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocPagesRotate200Response, error) {
	response, err := c.WithRawResponse.Rotate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
