// Code generated by Fern. DO NOT EDIT.

package doc_signatures_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	strings "strings"
	testing "testing"

	client "github.com/embedpdf/cloudpdf-sdk-go/v3/client"
	doc "github.com/embedpdf/cloudpdf-sdk-go/v3/doc"
	option "github.com/embedpdf/cloudpdf-sdk-go/v3/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestDocSignaturesListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &doc.ListSignaturesRequest{
		DocID:     "docId",
		LayerName: "layerName",
	}
	_, invocationErr := client.Doc.Signatures.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDocSignaturesListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDocSignaturesListWithWireMock", "GET", "/v1/docs/docId/layers/layerName/signatures", nil, 1)
}

func TestDocSignaturesAbortWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &doc.AbortSignaturesRequest{
		DocID:     "docId",
		LayerName: "layerName",
		SigningID: "signingId",
	}
	_, invocationErr := client.Doc.Signatures.Abort(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDocSignaturesAbortWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDocSignaturesAbortWithWireMock", "DELETE", "/v1/docs/docId/layers/layerName/signatures/signingId", nil, 1)
}

func TestDocSignaturesCompleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &doc.DocSignaturesCompleteRequest{
		DocID:     "docId",
		LayerName: "layerName",
		SigningID: "signingId",
		Cms:       "cms",
		ExpectedVersion: &doc.DocSignaturesCompleteRequestExpectedVersion{
			BaseSha256:   "baseSha256",
			EditsVersion: 1,
		},
	}
	_, invocationErr := client.Doc.Signatures.Complete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDocSignaturesCompleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDocSignaturesCompleteWithWireMock", "POST", "/v1/docs/docId/layers/layerName/signatures/signingId/complete", nil, 1)
}

func TestDocSignaturesAnalysisWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &doc.AnalysisSignaturesRequest{
		DocID:     "docId",
		LayerName: "layerName",
	}
	_, invocationErr := client.Doc.Signatures.Analysis(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDocSignaturesAnalysisWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDocSignaturesAnalysisWithWireMock", "GET", "/v1/docs/docId/layers/layerName/signatures/analysis", nil, 1)
}

func TestDocSignaturesPrepareWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &doc.PrepareSignaturesRequest{
		DocID:     "docId",
		LayerName: "layerName",
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.Doc.Signatures.Prepare(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDocSignaturesPrepareWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDocSignaturesPrepareWithWireMock", "POST", "/v1/docs/docId/layers/layerName/signatures/prepare", nil, 1)
}
