// Code generated by Fern. DO NOT EDIT.

package redactions

import (
	context "context"

	cloudpdf "github.com/embedpdf/cloudpdf-sdk-go/v3"
	core "github.com/embedpdf/cloudpdf-sdk-go/v3/core"
	doc "github.com/embedpdf/cloudpdf-sdk-go/v3/doc"
	internal "github.com/embedpdf/cloudpdf-sdk-go/v3/internal"
	option "github.com/embedpdf/cloudpdf-sdk-go/v3/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	request := &doc.ApplyRedactionsRequest{
//	    DocID: "docId",
//	    LayerName: "layerName",
//	    Body: map[string]any{
//	        "key": "value",
//	    },
//	}
//	client.Doc.Redactions.Apply(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Apply(
	ctx context.Context,
	request *doc.ApplyRedactionsRequest,
	opts ...option.RequestOption,
) (*cloudpdf.DocRedactionsApply200Response, error) {
	response, err := c.WithRawResponse.Apply(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
