// Code generated by Fern. DO NOT EDIT.

package tenants

import (
	context "context"

	cloudpdf "github.com/embedpdf/cloudpdf-sdk-go/v3"
	core "github.com/embedpdf/cloudpdf-sdk-go/v3/core"
	internal "github.com/embedpdf/cloudpdf-sdk-go/v3/internal"
	option "github.com/embedpdf/cloudpdf-sdk-go/v3/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	request := &cloudpdf.ListTenantsRequest{}
//	client.Tenants.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *cloudpdf.ListTenantsRequest,
	opts ...option.RequestOption,
) (*cloudpdf.TenantsList200Response, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &cloudpdf.TenantsCreateRequest{
//	    ID: "id",
//	}
//	client.Tenants.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *cloudpdf.TenantsCreateRequest,
	opts ...option.RequestOption,
) (*cloudpdf.TenantsCreate200Response, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &cloudpdf.GetTenantsRequest{
//	    TenantID: "tenantId",
//	}
//	client.Tenants.Get(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Get(
	ctx context.Context,
	request *cloudpdf.GetTenantsRequest,
	opts ...option.RequestOption,
) (*cloudpdf.TenantsGet200Response, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Destroys the tenant and everything in its namespace — documents, layers, stored bytes, audit history. Irreversible.
//
// Example:
//
//	request := &cloudpdf.DeleteTenantsRequest{
//	    TenantID: "tenantId",
//	}
//	client.Tenants.Delete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Delete(
	ctx context.Context,
	request *cloudpdf.DeleteTenantsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
